DDD: sns::Fixpoint Class Reference
sns::Fixpoint Class Reference
Public Member Functions
Fixpoint (const GShom &a, int ref=0, bool can_garbage=false)
bool operator== (const _GShom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GShom invert (const GSDD &pot) const
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Private Attributes
GShom arg
bool can_garbage
Constructor & Destructor Documentation
sns::Fixpoint::Fixpoint (const GShom & a, int ref = 0, bool can_garbage = false) [inline]
Referenced by clone().
Member Function Documentation
_GShom* sns::Fixpoint::clone () const [inline, virtual]
Implements _GShom.
References Fixpoint().
GSDD sns::Fixpoint::eval (const GSDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References sns::__fixpointObs, arg, can_garbage, GShom::DFS, sns::Add::partition::F, fixpoint(), sns::Add::partition::G, MemoryManager::garbage(), _GShom::get_concret(), GShom::getFixpointStrategy(), _GShom::GShom, sns::Add::partition::has_local, GShom::id, sns::Add::partition::L, localApply(), GShom::mark(), GSDD::mark(), GSDD::null, GSDD::one, _GShom::Shom, MemoryManager::should_garbage(), GSDD::top, IFixpointObserver::update(), and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
const GShom::range_t sns::Fixpoint::get_range () const [inline, virtual]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GShom.
References arg, and GShom::get_range().
size_t sns::Fixpoint::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References arg, and GShom::hash().
GShom sns::Fixpoint::invert (const GSDD & pot) const [inline, virtual]
Reimplemented from _GShom.
References arg, fixpoint(), GShom::id, and GShom::invert().
bool sns::Fixpoint::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
References arg, and GShom::is_selector().
void sns::Fixpoint::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References arg, and GShom::mark().
bool sns::Fixpoint::operator== (const _GShom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References arg.
void sns::Fixpoint::print (std::ostream & os) const [inline, virtual]
Implements _GShom.
References arg.
bool sns::Fixpoint::skip_variable (int) const [inline, virtual]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
References arg, and GShom::skip_variable().
Member Data Documentation
GShom sns::Fixpoint::arg [private]
Referenced by eval(), get_range(), hash(), invert(), is_selector(), mark(), operator==(), print(), and skip_variable().
bool sns::Fixpoint::can_garbage [private]
Referenced by eval().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.