DDD: GSDD Class Reference
GSDD Class Reference
This class is the base class representing a hierarchical Set Decision Diagram.
#include <SDD.h>
Public Member Functions
unsigned int refCounter () const
Returns current reference count of a node.
unsigned long int size () const
Returns the size in number of nodes of a SDD structure.
std::pair< unsigned long int,
unsigned long int > node_size () const
size_t nbsons () const
Returns the number of successors of a given node. This is the size of the arc array of the node.
long double nbStates () const
Returns the number of states or paths represented by a given node.
short int getHeight () const
Returns the height of the SDD node = max(son.height()) + 1 Terminals 0,1,T have height 0 by definition.
Public Constructors
GSDD (int variable, Valuation value)
Construct a GSDD with arguments given.
GSDD ()
Default constructor creates the empty set SDD.
GSDD (int var, const DataSet &val, const GSDD &d=one)
The most common way for the user of creating SDD.
GSDD (int var, const GSDD &val, const GSDD &d=one)
Another common way for the user to create SDD.
GSDD (int var, const class SDD &val, const GSDD &d=one)
GSDD (const _GSDD &_g)
A should be private constructor used in internals, DO NOT USE THIS.
GSDD (_GSDD *_g)
UNIMPLEMENTED DELIBERATELY: see SHom.h for details.
GSDD (const _GSDD *_g)
Comparisons for hash and map storage
bool operator== (const GSDD &g) const
Comparison between DDD.
bool operator!= (const GSDD &g) const
Comparison between DDD.
bool operator< (const GSDD &g) const
Total ordering function between DDD.
DataSet implementation interface
This is the implementation of the DataSet class interface used in SDD context.
These functions allow to reference SDD from SDD arcs. IMPORTANT Remember to delete returned values after use.
Note these functions are not resistant to incompatible DataSet types. When these functions have a parameter "b", it should be a reference to a SDD from proper behavior.
DataSet * newcopy () const
Return a new copy of a SDD.
DataSet * set_intersect (const DataSet &b) const
Compute intersection of two SDD.
DataSet * set_union (const DataSet &b) const
Compute union of two SDD.
DataSet * set_minus (const DataSet &b) const
Compute set difference of two SDD.
bool empty () const
Return true if this is the empty set.
DataSet * empty_set () const
Returns a pointer to GSDD::null.
bool set_equal (const DataSet &b) const
Compares to DataSet for equality.
bool set_less_than (const DataSet &b) const
Compares two sets with a total order.
long double set_size () const
Compares to DataSet for equality.
size_t set_hash () const
Returns a hash key for the SDD.
void set_print (std::ostream &os) const
Textual (human readable) output of a SDD.
Static Public Attributes
Terminal nodes defined as constants
static const GSDD one
The accepting terminal. This is the basic leaf for accepted sequences.
static const GSDD null
The non-accepting terminal.
static const GSDD top
The approximation terminal.
Private Member Functions
void print (std::ostream &os, std::string s) const
Internal function used in recursion for textual printing of GDDD.
Private Attributes
const _GSDD * concret
The real implementation class.
Friends
class SDD
Open access to concret for reference counting in DDD.
class _GSDD
open access to internal implementation class.
std::ostream & operator<< (std::ostream &os, const GSDD &g)
A textual output.
Public Accessors
typedef std::vector< std::pair
< DataSet *, GSDD > > Valuation
To hide how arcs are actually stored. Use GSDD::Valuation to refer to arcs type.
typedef Valuation::const_iterator const_iterator
To hide how arcs are stored.
int variable () const
Returns a node's variable.
const_iterator begin () const
API for iterating over the arcs of a DDD manually.
const_iterator end () const
API for iterating over the arcs of a DDD manually.
Memory Management
Broken right now, dont use me or fixme first Returns the number of nodes that would be used to represent a SDD if no unicity table was used.
void mark () const
For garbage collection internals.
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Returns unicity table current size. Gives the number of different nodes created and not yet destroyed.
static void garbage ()
For garbage collection, do not call this directly, use MemoryManager::garbage() instead.
static void pstats (bool reinit=true)
Prints some statistics to std::cout.
static size_t peak ()
Returns the peak size of the DDD unicity table. This value is maintained up to date upon GarbageCollection.
Detailed Description
This class is the base class representing a hierarchical Set Decision Diagram.
It is composed of a set of arcs labeled by sets of values (DataSet in fact) that point to successor GSDD nodes. This class does not implement reference counting : GSDD are destroyed on MemoryManager::Garbage unless they are also referenced as SDD. Note that this class is in fact a kind of smart pointer : operations are delegated on "concret" the true implementation class (of private hidden type _GSDD) that contains the data and has a single memory occurrence thanks to the unicity table.
Member Typedef Documentation
typedef Valuation::const_iterator GSDD::const_iterator
To hide how arcs are stored.
Also for more compact expressions : use GDDD::const_iterator to iterate over the arcs of a DDD
typedef std::vector<std::pair<DataSet *,GSDD> > GSDD::Valuation
To hide how arcs are actually stored. Use GSDD::Valuation to refer to arcs type.
Constructor & Destructor Documentation
GSDD::GSDD (int variable, Valuation value)
Construct a GSDD with arguments given.
Parameters:
variable the variable labeling the node
value the outgoing arc of the node
References _GSDD, canonical, concret, and null.
GSDD::GSDD () [inline]
Default constructor creates the empty set SDD.
Referenced by empty_set(), newcopy(), set_intersect(), set_minus(), and set_union().
GSDD::GSDD (int var, const DataSet & val, const GSDD & d = one)
The most common way for the user of creating SDD.
This constructor builds a node with a single arc of the form var-val->d. Usually a user will create these single path SDD, possibly by imbrication as in GSDD(var1, val1, GSDD(var2, val2)). Then compose them using +, -, *, ^ ...
Parameters:
var the variable labeling the node
val the value labeling the arc
d the successor node or defaults to terminal GSDD::one if none provided
References _GSDD, canonical, concret, DataSet::empty(), DataSet::newcopy(), null, and _GSDD::valuation.
GSDD::GSDD (int var, const GSDD & val, const GSDD & d = one)
Another common way for the user to create SDD.
This constructor builds a node with a single arc of the form var-val->d. This adapted version is useful when the arc value is itself the result of Hom applications as the compiler needs the change from GSDD to SDD type to recognize a DataSet
Parameters:
var the variable labeling the node
val the value labeling the arc
d the successor node or defaults to terminal GSDD::one if none provided
References _GSDD, canonical, concret, empty(), newcopy(), null, and _GSDD::valuation.
GSDD::GSDD (int var, const class SDD & val, const GSDD & d = one)
GSDD::GSDD (const _GSDD & _g)
A should be private constructor used in internals, DO NOT USE THIS.
Calls canonical to uniquify the pointer provided
GSDD::GSDD (_GSDD * _g)
UNIMPLEMENTED DELIBERATELY: see SHom.h for details.
user should use version above const & or below const * into unique storage.
GSDD::GSDD (const _GSDD * _g)
Parameters:
_g The pointer provided should point into the unicity table
Member Function Documentation
GSDD::const_iterator GSDD::begin () const
API for iterating over the arcs of a DDD manually.
i.e. not using a predefined evaluation mechanism such as StrongHom
for (GDDD::const_iterator it = a_gddd.begin() ; it != a_gddd.end() ; it++) { // do something }
returns the first arc
References concret, and _GSDD::valuation.
Referenced by hDotExporter::collect(), dotExporter::collect(), StrongShom::eval(), sns::SLocalApply::eval(), sns::LocalApply::eval(), sns::DomExtract::eval(), sns::Mult::eval(), _SDED_Concat::eval(), _SDED_Minus::eval(), _SDED_Mult::eval(), _GShom::eval_skip(), sns::SLocalApply::invert(), sns::LocalApply::invert(), MySDDNbStates::nbStates(), print(), dotExporter::printColor(), and SddSize::sddsize().
bool GSDD::empty () const [virtual]
Return true if this is the empty set.
Implements DataSet.
References null.
Referenced by GSDD().
DataSet * GSDD::empty_set () const [virtual]
Returns a pointer to GSDD::null.
Implements DataSet.
References GSDD().
GSDD::const_iterator GSDD::end () const
API for iterating over the arcs of a DDD manually.
i.e. not using a predefined evaluation mechanism such as StrongHom
for (GDDD::const_iterator it = a_gddd.begin() ; it != a_gddd.end() ; it++) { // do something }
returns a past the end iterator
References concret, and _GSDD::valuation.
Referenced by hDotExporter::collect(), dotExporter::collect(), StrongShom::eval(), sns::SLocalApply::eval(), sns::LocalApply::eval(), sns::DomExtract::eval(), sns::Mult::eval(), _SDED_Concat::eval(), _SDED_Minus::eval(), _SDED_Mult::eval(), _GShom::eval_skip(), MySDDNbStates::nbStates(), print(), dotExporter::printColor(), and SddSize::sddsize().
void GSDD::garbage () [static]
For garbage collection, do not call this directly, use MemoryManager::garbage() instead.
Todo:
describe garbage collection algorithm(s) + mark usage homogeneously in one place.
References MySDDNbStates::clear(), _GSDD::marking, Max_SDD, UniqueTable< T >::size(), and UniqueTable< T >::table.
short GSDD::getHeight () const
Returns the height of the SDD node = max(son.height()) + 1 Terminals 0,1,T have height 0 by definition.
References concret, and _GSDD::getHeight().
size_t GSDD::hash () const [inline]
For storage in a hash table.
References concret, and ddd::knuth32_hash().
Referenced by _SDED_Mult::create(), sns::Minus::hash(), sns::RightConcat::hash(), sns::LeftConcat::hash(), sns::Mult::hash(), sns::Constant::hash(), _SDED_Shom::hash(), _SDED_Concat::hash(), _SDED_Minus::hash(), _SDED_Mult::hash(), and _SDED_GSDD::hash().
void GSDD::mark () const
For garbage collection internals.
Marks a GSDD as in use in garbage collection phase.
References concret, and _GSDD::mark().
Referenced by sns::Fixpoint::eval(), sns::Minus::mark(), sns::RightConcat::mark(), sns::LeftConcat::mark(), sns::Mult::mark(), and sns::Constant::mark().
size_t GSDD::nbsons () const
Returns the number of successors of a given node. This is the size of the arc array of the node.
References concret, and _GSDD::valuation.
Referenced by _GShom::eval_skip().
long double GSDD::nbStates () const
Returns the number of states or paths represented by a given node.
Referenced by Statistic::load(), and set_size().
DataSet* GSDD::newcopy () const [inline, virtual]
Return a new copy of a SDD.
Implements DataSet.
References GSDD().
Referenced by GSDD().
std::pair< unsigned long int, unsigned long int > GSDD::node_size () const
References SddSize::d3res, and SddSize::res.
Referenced by Statistic::load().
bool GSDD::operator!= (const GSDD & g) const [inline]
Comparison between DDD.
Note that comparison is based on "concret" address in unicity table.
Parameters:
g the node to compare to
Returns:
true if the nodes are not equal.
References concret.
bool GSDD::operator< (const GSDD & g) const
Total ordering function between DDD.
Note that comparison is based on "concret" address in unicity table. This ordering is necessary for hash and map storage of GDDD.
Parameters:
g the node to compare to
Returns:
true if argument g is greater than "this" node.
References concret.
bool GSDD::operator== (const GSDD & g) const [inline]
Comparison between DDD.
Note that comparison is based on "concret" address in unicity table.
Parameters:
g the node to compare to
Returns:
true if the nodes are equal.
References concret.
size_t GSDD::peak () [static]
Returns the peak size of the DDD unicity table. This value is maintained up to date upon GarbageCollection.
References Max_SDD, and UniqueTable< T >::size().
Referenced by Statistic::load(), and pstats().
void GSDD::print (std::ostream & os, std::string s) const [private]
Internal function used in recursion for textual printing of GDDD.
References begin(), end(), null, one, top, and variable().
Referenced by operator<<().
void GSDD::pstats (bool reinit = true) [static]
Prints some statistics to std::cout.
Mostly used in debug and development phase. See also MemoryManager::pstats().
Todo:
allow output in other place than cout. Clean up output.
References peak().
unsigned int GSDD::refCounter () const
Returns current reference count of a node.
Reference count corresponds to the number of SDD that use a given concrete node. No recursive reference counting is used : son nodes may have refCount=0 even if this node has a positive refCounter.
References concret, and _GSDD::refCounter.
bool GSDD::set_equal (const DataSet & b) const [virtual]
Compares to DataSet for equality.
Implements DataSet.
size_t GSDD::set_hash () const [virtual]
Returns a hash key for the SDD.
Implements DataSet.
References concret.
DataSet * GSDD::set_intersect (const DataSet & b) const [virtual]
Compute intersection of two SDD.
Implements DataSet.
References GSDD().
bool GSDD::set_less_than (const DataSet & b) const [virtual]
Compares two sets with a total order.
Implements DataSet.
DataSet * GSDD::set_minus (const DataSet & b) const [virtual]
Compute set difference of two SDD.
Implements DataSet.
References GSDD().
void GSDD::set_print (std::ostream & os) const [inline, virtual]
Textual (human readable) output of a SDD.
Implements DataSet.
long double GSDD::set_size () const [virtual]
Compares to DataSet for equality.
Implements DataSet.
References nbStates().
DataSet * GSDD::set_union (const DataSet & b) const [virtual]
Compute union of two SDD.
Implements DataSet.
References GSDD().
unsigned long int GSDD::size () const
Returns the size in number of nodes of a SDD structure.
unsigned int GSDD::statistics () [static]
Returns unicity table current size. Gives the number of different nodes created and not yet destroyed.
References UniqueTable< T >::size().
Referenced by MemoryManager::nbSDD().
int GSDD::variable () const
Returns a node's variable.
References concret, and _GSDD::variable.
Referenced by hDotExporter::collect(), dotExporter::collect(), _SDED_Minus::create(), _SDED_Mult::create(), _SDED_Add::create(), StrongShom::eval(), sns::Fixpoint::eval(), sns::Add::eval(), sns::And::eval(), sns::SLocalApply::eval(), sns::LocalApply::eval(), sns::DomExtract::eval(), sns::Mult::eval(), _SDED_Concat::eval(), _SDED_Minus::eval(), _SDED_Mult::eval(), _GShom::eval_skip(), and print().
Friends And Related Function Documentation
friend class _GSDD [friend]
open access to internal implementation class.
Referenced by GSDD().
std::ostream& operator<< (std::ostream & os, const GSDD & g) [friend]
A textual output.
Don't use it with large number of paths as each element is printed on a different line
friend class SDD [friend]
Open access to concret for reference counting in DDD.
Member Data Documentation
const _GSDD* GSDD::concret [private]
The real implementation class.
All true operations are delagated on this pointer. Construction/destruction take care of ensuring concret is only instantiated once in memory.
Referenced by begin(), end(), getHeight(), GSDD(), hash(), mark(), nbsons(), operator!=(), operator<(), SDD::operator=(), operator==(), refCounter(), SDD::SDD(), set_hash(), variable(), and SDD::~SDD().
const GSDD GSDD::null [static]
The non-accepting terminal.
As DDD are a zero-suppressed variant of decision diagrams, paths leading to null are suppressed. Only the empty set is represented by null.
Referenced by _SDED_Shom::create(), _SDED_Concat::create(), _SDED_Minus::create(), _SDED_Mult::create(), _SDED_Add::create(), empty(), StrongShom::eval(), sns::Fixpoint::eval(), sns::Add::eval(), sns::And::eval(), sns::SNotCond::eval(), sns::SLocalApply::eval(), sns::LocalApply::eval(), sns::DomExtract::eval(), sns::Mult::eval(), sns::Constant::eval(), _SDED_Concat::eval(), _SDED_Minus::eval(), _SDED_Mult::eval(), _SDED_Add::eval(), _GShom::eval_skip(), GSDD(), sns::Constant::is_selector(), MySDDNbStates::nbStates(), GShom::operator()(), and print().
const GSDD GSDD::one [static]
The accepting terminal. This is the basic leaf for accepted sequences.
Referenced by hDotExporter::collect(), dotExporter::collect(), _SDED_Concat::create(), _SDED_Minus::create(), _SDED_Mult::create(), _SDED_Add::create(), StrongShom::eval(), sns::Fixpoint::eval(), sns::Add::eval(), sns::And::eval(), sns::SNotCond::eval(), sns::SLocalApply::eval(), sns::LocalApply::eval(), sns::DomExtract::eval(), _GShom::eval_skip(), MySDDNbStates::nbStates(), and print().
const GSDD GSDD::top [static]
The approximation terminal.
This represents *any* finite set of assignment sequences. In a "normal" usage pattern, top terminals should not be produced. In fact the result may be incorrect if Top is encountered at any but the highest level.
Referenced by hDotExporter::collect(), dotExporter::collect(), _SDED_Concat::create(), _SDED_Minus::create(), _SDED_Mult::create(), _SDED_Add::create(), StrongShom::eval(), sns::Fixpoint::eval(), sns::Add::eval(), sns::And::eval(), sns::SNotCond::eval(), sns::SLocalApply::eval(), sns::LocalApply::eval(), sns::DomExtract::eval(), _GShom::eval_skip(), MySDDNbStates::nbStates(), StrongShom::phiOne(), and print().
The documentation for this class was generated from the following files:
SDD.h
SDD.cpp
Please comment this page and report errors about it on the RefDocComments page.