DDD: MyGHom Class Reference
MyGHom Class Reference
Unknown function for this class.
#include <Hom.h>
Public Member Functions
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual GHom invert (const GDDD &) const
returns the predescessor homomorphism, using pot to determine variable domains
virtual bool operator== (const _GHom &h) const =0
Comparator.
virtual size_t hash () const =0
Hash key computation.
virtual _GHom * clone () const =0
virtual GDDD eval (const GDDD &) const =0
The computation function responsible for evaluation over a node.
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GHom compose (const GHom &r) const
virtual void print (std::ostream &os) const =0
Protected Member Functions
const _GHom * get_concret (const GHom &ghom) const
Detailed Description
Unknown function for this class.
Todo:
: What IS this for ? get rid of it.
Member Function Documentation
virtual _GHom* _GHom::clone () const [pure virtual, inherited]
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
GHom _GHom::compose (const GHom & r) const [virtual, inherited]
References _GHom::GHom.
Referenced by GHom::compose().
virtual GDDD _GHom::eval (const GDDD &) const [pure virtual, inherited]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, MLHomAdapter, and StrongHom.
Referenced by _GHom::eval_skip(), and GHom::operator()().
const _GHom* _GHom::get_concret (const GHom & ghom) const [inline, protected, inherited]
References GHom::concret.
Referenced by Add::Add(), Fixpoint::eval(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
virtual size_t _GHom::hash () const [pure virtual, inherited]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
virtual GHom _GHom::invert (const GDDD &) const [inline, virtual, inherited]
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented in Identity, Constant, Mult, Add, Compose, Minus, and Fixpoint.
References _GHom::GHom, _GHom::is_selector(), GDDD::null, and _GHom::print().
Referenced by GHom::invert().
virtual bool _GHom::is_selector () const [inline, virtual, inherited]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in Identity, Mult, NotCond, Add, Compose, Minus, and Fixpoint.
Referenced by _GHom::invert(), and GHom::is_selector().
virtual void _GHom::mark () const [inline, virtual, inherited]
For garbage collection. Used in first phase of garbage collection.
Reimplemented in Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
Referenced by GHom::mark().
virtual bool _GHom::operator== (const _GHom & h) const [pure virtual, inherited]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, MLHomAdapter, and StrongHom.
virtual void _GHom::print (std::ostream & os) const [pure virtual, inherited]
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, MLHomAdapter, and StrongHom.
Referenced by _GHom::invert(), and operator<<().
virtual bool _GHom::skip_variable (int) const [inline, virtual, inherited]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in Identity, NotCond, Add, Compose, RightConcat, and Fixpoint.
Referenced by _GHom::eval_skip(), GHom::skip_variable(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
The documentation for this class was generated from the following file:
Hom.h
Please comment this page and report errors about it on the RefDocComments page.