DDD: _DED_GDDD Class Reference
_DED_GDDD Class Reference
Public Member Functions
_DED_GDDD (const GDDD &g)
size_t hash () const
bool operator== (const _DED &e) const
_DED * clone () const
GDDD eval () const
Private Attributes
GDDD parameter
Constructor & Destructor Documentation
_DED_GDDD::_DED_GDDD (const GDDD & g) [inline]
Referenced by clone().
Member Function Documentation
_DED* _DED_GDDD::clone () const [inline, virtual]
Implements _DED.
References _DED_GDDD().
GDDD _DED_GDDD::eval () const [inline, virtual]
Implements _DED.
References parameter.
size_t _DED_GDDD::hash () const [inline, virtual]
Implements _DED.
References GDDD::hash(), and parameter.
bool _DED_GDDD::operator== (const _DED & e) const [inline, virtual]
Implements _DED.
References parameter.
Member Data Documentation
GDDD _DED_GDDD::parameter [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
DED.cpp
Please comment this page and report errors about it on the RefDocComments page.