DDD: Cache< HomType, NodeType > Class Template Reference
Cache< HomType, NodeType > Class Template Reference
#include <Cache.hh>
Public Member Functions
Cache ()
void clear (bool keepstats=false)
clear the cache, discarding all values.
size_t peak () const
size_t size () const
std::pair< bool, NodeType > insert (const HomType &hom, const NodeType &node)
Private Types
typedef hash_map< std::pair
< HomType, NodeType >
, NodeType >::type hash_map
Private Attributes
size_t peak_
hash_map cache_
template<typename HomType, typename NodeType>
class Cache< HomType, NodeType >
Member Typedef Documentation
template<typename HomType , typename NodeType > typedef hash_map< std::pair<HomType, NodeType>, NodeType >::type Cache< HomType, NodeType >::hash_map [private]
Constructor & Destructor Documentation
template<typename HomType , typename NodeType > Cache< HomType, NodeType >::Cache () [inline]
Member Function Documentation
template<typename HomType , typename NodeType > void Cache< HomType, NodeType >::clear (bool keepstats = false) [inline]
clear the cache, discarding all values.
References Cache< HomType, NodeType >::cache_, ext_hash_map< Key, Data, HashKey, EqualKey >::clear(), and Cache< HomType, NodeType >::peak().
Referenced by GHom::garbage().
template<typename HomType , typename NodeType > std::pair<bool,NodeType> Cache< HomType, NodeType >::insert (const HomType & hom, const NodeType & node) [inline]
References Cache< HomType, NodeType >::cache_, ext_hash_map< Key, Data, HashKey, EqualKey >::find(), and ext_hash_map< Key, Data, HashKey, EqualKey >::insert().
Referenced by SDED::eval(), DED::eval(), and GHom::operator()().
template<typename HomType , typename NodeType > size_t Cache< HomType, NodeType >::peak () const [inline]
References Cache< HomType, NodeType >::peak_, and Cache< HomType, NodeType >::size().
Referenced by Cache< HomType, NodeType >::clear().
template<typename HomType , typename NodeType > size_t Cache< HomType, NodeType >::size () const [inline]
References Cache< HomType, NodeType >::cache_, and ext_hash_map< Key, Data, HashKey, EqualKey >::size().
Referenced by SDED::garbage(), DED::garbage(), SDED::peak(), DED::peak(), Cache< HomType, NodeType >::peak(), DED::pstats(), SDED::statistics(), and DED::statistics().
Member Data Documentation
template<typename HomType , typename NodeType > hash_map Cache< HomType, NodeType >::cache_ [private]
Referenced by Cache< HomType, NodeType >::clear(), Cache< HomType, NodeType >::insert(), and Cache< HomType, NodeType >::size().
template<typename HomType , typename NodeType > size_t Cache< HomType, NodeType >::peak_ [mutable, private]
Referenced by Cache< HomType, NodeType >::peak().
The documentation for this class was generated from the following file:
Cache.hh
Please comment this page and report errors about it on the RefDocComments page.