DDD: _DED_Hom Class Reference
_DED_Hom Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _DED &e) const
_DED * clone () const
GDDD eval () const
~_DED_Hom ()
Static Public Member Functions
static _DED * create (const GHom &h, const GDDD &d)
Private Member Functions
_DED_Hom (const GHom &h, const GDDD &d)
Private Attributes
GHom hom
GDDD parameter
Constructor & Destructor Documentation
_DED_Hom::_DED_Hom (const GHom & h, const GDDD & d) [inline, private]
Referenced by clone(), and create().
_DED_Hom::~_DED_Hom () [inline]
Member Function Documentation
_DED* _DED_Hom::clone () const [inline, virtual]
Implements _DED.
References _DED_Hom().
_DED * _DED_Hom::create (const GHom & h, const GDDD & d) [static]
References _DED_Hom(), and GDDD::null.
Referenced by DED::hom().
GDDD _DED_Hom::eval () const [virtual]
Implements _DED.
References GHom::eval(), hom, and parameter.
size_t _DED_Hom::hash () const [virtual]
Implements _DED.
References GDDD::hash(), GHom::hash(), hom, and parameter.
bool _DED_Hom::operator== (const _DED & e) const [virtual]
Implements _DED.
References hom, and parameter.
Member Data Documentation
GHom _DED_Hom::hom [private]
Referenced by eval(), hash(), and operator==().
GDDD _DED_Hom::parameter [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
DED.cpp
Please comment this page and report errors about it on the RefDocComments page.