DDD: AdditiveMap< K, V > Class Template Reference
AdditiveMap< K, V > Class Template Reference
#include <AdditiveMap.hpp>
Public Types
typedef mapType::value_type value_type
typedef mapType::const_iterator const_iterator
typedef mapType::iterator iterator
Public Member Functions
AdditiveMap ()
const_iterator end () const
const_iterator begin () const
iterator find (const K &key)
int addAll (const AdditiveMap< K, V > &other)
int addAll (const_iterator begin, const_iterator end)
bool add (const K &key, const V &value)
bool remove (const K &key, const V &value)
Private Types
typedef std::map< K, V > mapType
Private Attributes
mapType map
template<typename K, typename V>
class AdditiveMap< K, V >
Member Typedef Documentation
template<typename K, typename V> typedef mapType::const_iterator AdditiveMap< K, V >::const_iterator
template<typename K, typename V> typedef mapType::iterator AdditiveMap< K, V >::iterator
template<typename K, typename V> typedef std::map<K,V> AdditiveMap< K, V >::mapType [private]
template<typename K, typename V> typedef mapType::value_type AdditiveMap< K, V >::value_type
Constructor & Destructor Documentation
template<typename K, typename V> AdditiveMap< K, V >::AdditiveMap () [inline]
Member Function Documentation
template<typename K, typename V> bool AdditiveMap< K, V >::add (const K & key, const V & value) [inline]
References AdditiveMap< K, V >::map.
Referenced by AdditiveMap< K, V >::addAll(), StrongMLHom::eval(), nsMLHom::LeftConcat::eval(), nsMLHom::ConstantUp::eval(), nsMLHom::GHomAdapter::eval(), and nsMLHom::Identity::eval().
template<typename K, typename V> int AdditiveMap< K, V >::addAll (const_iterator begin, const_iterator end) [inline]
References AdditiveMap< K, V >::add().
template<typename K, typename V> int AdditiveMap< K, V >::addAll (const AdditiveMap< K, V > & other) [inline]
References AdditiveMap< K, V >::begin(), and AdditiveMap< K, V >::end().
Referenced by nsMLHom::Add::eval().
template<typename K, typename V> const_iterator AdditiveMap< K, V >::begin () const [inline]
References AdditiveMap< K, V >::map.
Referenced by AdditiveMap< K, V >::addAll(), StrongMLHom::eval(), nsMLHom::LeftConcat::eval(), nsMLHom::ConstantUp::eval(), and MLHomAdapter::eval().
template<typename K, typename V> const_iterator AdditiveMap< K, V >::end () const [inline]
References AdditiveMap< K, V >::map.
Referenced by AdditiveMap< K, V >::addAll(), StrongMLHom::eval(), nsMLHom::LeftConcat::eval(), nsMLHom::ConstantUp::eval(), and MLHomAdapter::eval().
template<typename K, typename V> iterator AdditiveMap< K, V >::find (const K & key) [inline]
References AdditiveMap< K, V >::map.
template<typename K, typename V> bool AdditiveMap< K, V >::remove (const K & key, const V & value) [inline]
References AdditiveMap< K, V >::map.
Member Data Documentation
template<typename K, typename V> mapType AdditiveMap< K, V >::map [private]
Referenced by AdditiveMap< K, V >::add(), AdditiveMap< K, V >::begin(), AdditiveMap< K, V >::end(), AdditiveMap< K, V >::find(), and AdditiveMap< K, V >::remove().
The documentation for this class was generated from the following file:
AdditiveMap.hpp
Please comment this page and report errors about it on the RefDocComments page.