DDD: nsMLHom::GHomAdapter Class Reference
nsMLHom::GHomAdapter Class Reference
Public Member Functions
GHomAdapter (const GHom &_h, int ref=0)
bool operator== (const _MLHom &other) const
size_t hash () const
unique table trivia
_MLHom * clone () const
bool skip_variable (int var) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
GHom h
Constructor & Destructor Documentation
nsMLHom::GHomAdapter::GHomAdapter (const GHom & _h, int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_MLHom* nsMLHom::GHomAdapter::clone () const [inline, virtual]
Implements _MLHom.
References GHomAdapter().
HomNodeMap nsMLHom::GHomAdapter::eval (const GDDD & d) const [inline, virtual]
Implements _MLHom.
References AdditiveMap< K, V >::add(), h, and GHom::id.
size_t nsMLHom::GHomAdapter::hash () const [inline, virtual]
unique table trivia
Implements _MLHom.
References h, and GHom::hash().
bool nsMLHom::GHomAdapter::operator== (const _MLHom & other) const [inline, virtual]
Implements _MLHom.
References h.
virtual bool _MLHom::shouldCache () const [inline, virtual, inherited]
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
bool nsMLHom::GHomAdapter::skip_variable (int var) const [inline]
References h, and GHom::skip_variable().
Member Data Documentation
GHom nsMLHom::GHomAdapter::h [private]
Referenced by eval(), hash(), operator==(), and skip_variable().
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.