DDD: sns::SNotCond Class Reference
sns::SNotCond Class Reference
Public Member Functions
SNotCond (const GShom &cond)
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
size_t hash () const
Hash key computation.
bool operator== (const _GShom &s) const
Comparator.
_GShom * clone () const
void print (std::ostream &os) const
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Public Attributes
GShom cond_
Constructor & Destructor Documentation
sns::SNotCond::SNotCond (const GShom & cond) [inline]
Referenced by clone().
Member Function Documentation
_GShom* sns::SNotCond::clone () const [inline, virtual]
Implements _GShom.
References SNotCond().
GSDD sns::SNotCond::eval (const GSDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References cond_, GSDD::null, GSDD::one, and GSDD::top.
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
const GShom::range_t sns::SNotCond::get_range () const [inline, virtual]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GShom.
References cond_, and GShom::get_range().
size_t sns::SNotCond::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References cond_, and GShom::hash().
virtual GShom _GShom::invert (const GSDD &) const [inline, virtual, inherited]
Reimplemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::And, sns::Add, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
bool sns::SNotCond::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
void sns::SNotCond::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References cond_, and GShom::mark().
bool sns::SNotCond::operator== (const _GShom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References cond_.
void sns::SNotCond::print (std::ostream & os) const [inline, virtual]
Implements _GShom.
References cond_.
bool sns::SNotCond::skip_variable (int) const [inline, virtual]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
References cond_, and GShom::skip_variable().
Member Data Documentation
GShom sns::SNotCond::cond_
Referenced by eval(), get_range(), hash(), mark(), operator==(), print(), and skip_variable().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.