DDD: hDotExporter Class Reference
hDotExporter Class Reference
Public Types
typedef d3::hash_set< GSDD >::type gsdd_hash_set
Public Member Functions
hDotExporter (const string &s="test", bool multiT=false)
virtual ~hDotExporter ()
void collect (const GSDD &g)
void collect (const GDDD &g)
void printColor (const GSDD &g, const string &color, gsdd_hash_set &visited)
void setColor (const GSDD &g, const string &color)
void init ()
int operator() (const GSDD &g)
void finish ()
Protected Member Functions
void collect (const SDD &g)
void collect (const DDD &g)
Protected Attributes
map< GSDD, string > name
map< GDDD, string > d3name
map< GDDD, string > entryd3Name
map< GDDD, int > entryd3Nb
map< GSDD, string > entryName
map< GSDD, int > entryNb
int nextid
int nextPid
int nextMid
int nextAid
string path
ostream * D3out
ostream * out
bool multiT
Member Typedef Documentation
typedef d3::hash_set<GSDD>::type dotExporter::gsdd_hash_set [inherited]
Constructor & Destructor Documentation
hDotExporter::hDotExporter (const string & s = "test", bool multiT = false) [inline]
virtual hDotExporter::~hDotExporter () [inline, virtual]
Member Function Documentation
void dotExporter::collect (const GDDD & g) [inline, inherited]
References GDDD::begin(), dotExporter::collect(), dotExporter::d3name, dotExporter::D3out, GDDD::end(), GDDD::getvarName(), dotExporter::nextid, GDDD::null, GDDD::one, GDDD::top, and GDDD::variable().
void dotExporter::collect (const DDD & g) [inline, protected, inherited]
References dotExporter::collect().
void dotExporter::collect (const SDD & g) [inline, protected, inherited]
Referenced by dotHighlight::addSDD(), collect(), dotExporter::collect(), dotExporter::operator()(), and dotExporter::setColor().
void hDotExporter::collect (const GSDD & g) [inline, virtual]
Reimplemented from dotExporter.
References GSDD::begin(), dotExporter::collect(), GSDD::end(), dotExporter::entryd3Name, dotExporter::entryd3Nb, dotExporter::name, dotExporter::nextAid, dotExporter::nextid, dotExporter::nextPid, GSDD::one, dotExporter::out, GSDD::top, and GSDD::variable().
void dotExporter::finish () [inline, inherited]
References dotExporter::d3name, dotExporter::D3out, dotExporter::entryd3Name, dotExporter::entryd3Nb, dotExporter::entryName, dotExporter::entryNb, dotExporter::name, and dotExporter::out.
Referenced by dotHighlight::exportDot(), and dotExporter::operator()().
void dotExporter::init () [inline, inherited]
References dotExporter::d3name, dotExporter::D3out, dotExporter::entryd3Name, dotExporter::entryd3Nb, dotExporter::entryName, dotExporter::entryNb, dotExporter::name, dotExporter::nextAid, dotExporter::nextid, dotExporter::nextMid, dotExporter::nextPid, dotExporter::out, and dotExporter::path.
Referenced by dotHighlight::initialize(), and dotExporter::operator()().
int dotExporter::operator() (const GSDD & g) [inline, inherited]
References dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
void dotExporter::printColor (const GSDD & g, const string & color, gsdd_hash_set & visited) [inline, inherited]
References GSDD::begin(), GSDD::end(), dotExporter::name, and dotExporter::out.
Referenced by dotExporter::setColor().
void dotExporter::setColor (const GSDD & g, const string & color) [inline, inherited]
References dotExporter::collect(), and dotExporter::printColor().
Referenced by dotHighlight::setColor().
Member Data Documentation
map<GDDD,string> dotExporter::d3name [protected, inherited]
Referenced by dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
ostream* dotExporter::D3out [protected, inherited]
Referenced by dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
map<GDDD,string> dotExporter::entryd3Name [protected, inherited]
Referenced by collect(), dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
map<GDDD,int> dotExporter::entryd3Nb [protected, inherited]
Referenced by collect(), dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
map<GSDD,string> dotExporter::entryName [protected, inherited]
Referenced by dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
map<GSDD,int> dotExporter::entryNb [protected, inherited]
Referenced by dotExporter::collect(), dotExporter::finish(), and dotExporter::init().
bool dotExporter::multiT [protected, inherited]
Referenced by dotExporter::collect().
map<GSDD,string> dotExporter::name [protected, inherited]
Referenced by collect(), dotExporter::collect(), dotExporter::finish(), dotExporter::init(), and dotExporter::printColor().
int dotExporter::nextAid [protected, inherited]
Referenced by collect(), dotExporter::collect(), and dotExporter::init().
int dotExporter::nextid [protected, inherited]
Referenced by collect(), dotExporter::collect(), and dotExporter::init().
int dotExporter::nextMid [protected, inherited]
Referenced by dotExporter::init().
int dotExporter::nextPid [protected, inherited]
Referenced by collect(), dotExporter::collect(), and dotExporter::init().
ostream* dotExporter::out [protected, inherited]
Referenced by collect(), dotExporter::collect(), dotExporter::finish(), dotExporter::init(), and dotExporter::printColor().
string dotExporter::path [protected, inherited]
Referenced by dotExporter::init().
The documentation for this class was generated from the following file:
util/dotExporter.cpp
Please comment this page and report errors about it on the RefDocComments page.