DDD: GDDD Class Reference
GDDD Class Reference
This class is the base class representing a Data Decision Diagram.
#include <DDD.h>
Public Member Functions
unsigned int refCounter () const
Returns current reference count of a node.
unsigned long int size () const
Returns the size in number of nodes of a DDD structure.
size_t nbsons () const
Returns the number of successors of a given node. This is the size of the arc array of the node.
long double nbStates () const
Returns the number of states or paths represented by a given node.
long double noSharedSize () const
Returns the number of nodes that would be used to represent a DDD if no unicity table was used.
Public Constructors
GDDD (int variable, Valuation value)
Construct a GDDD with arguments given.
GDDD ()
Default constructor creates the empty set DDD.
GDDD (int var, int val, const GDDD &d=one)
The most common way for the user of creating DDD.
GDDD (int var, int val1, int val2, const GDDD &d=one)
To create a DDD with arcs covering a range of values.
Comparisons for hash and map storage
bool operator== (const GDDD &g) const
Comparison between DDD.
bool operator!= (const GDDD &g) const
Comparison between DDD.
bool operator< (const GDDD &g) const
Total ordering function between DDD.
Static Public Member Functions
Variable naming.
static void varName (int var, const std::string &name)
Sets a variable's name.
static const std::string getvarName (int var)
Gets a variable's name.
Static Public Attributes
Terminal nodes defined as constants
static const GDDD one
The accepting terminal. This is the basic leaf for accepted sequences.
static const GDDD null
The non-accepting terminal.
static const GDDD top
The approximation terminal.
Private Member Functions
GDDD (const _GDDD *_g)
A private constructor used in internals.
GDDD (_GDDD *_g)
UNIMPLEMENTED DELIBERATELY: see SHom.h for details.
GDDD (const _GDDD &_g)
void print (std::ostream &os, std::string s) const
Internal function used in recursion for textual printing of GDDD.
void saveNode (std::ostream &, std::vector< const _GDDD * > &) const
A function for DDD serialization (beta).
unsigned long int nodeIndex (const std::vector< const _GDDD * > &) const
Another function used in serialization.
Private Attributes
const _GDDD * concret
The real implementation class.
Friends
class DDD
Open access to concret for reference counting in DDD.
std::ostream & operator<< (std::ostream &os, const GDDD &g)
A textual output.
Serialization functions.
void saveDDD (std::ostream &, std::vector< DDD >)
Function for serialization. Save a set of DDD to a stream.
void loadDDD (std::istream &, std::vector< DDD > &)
Function for deserialization. Load a set of DDD from a stream.
Public Accessors
typedef std::vector< std::pair
< int, GDDD > > Valuation
To hide how arcs are actually stored. Use GDDD::Valuation to refer to arcs type.
typedef Valuation::const_iterator const_iterator
To hide how arcs are stored.
int variable () const
Returns a node's variable.
const_iterator begin () const
API for iterating over the arcs of a DDD manually.
const_iterator end () const
API for iterating over the arcs of a DDD manually.
Memory Management
void mark () const
For garbage collection internals.
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Returns unicity table current size. Gives the number of different nodes created and not yet destroyed.
static void garbage ()
For garbage collection, do not call this directly, use MemoryManager::garbage() instead.
static void pstats (bool reinit=true)
Prints some statistics to std::cout.
static size_t peak ()
Returns the peak size of the DDD unicity table. This value is maintained up to date upon GarbageCollection.
Detailed Description
This class is the base class representing a Data Decision Diagram.
It is composed of a set of arcs labeled by integers that point to successor GDDD nodes. This class does not implement reference counting : GDDD are destroyed on MemoryManager::Garbage unless they are also referenced as DDD. Note that this class is in fact a kind of smart pointer : operations are delegated on "concret" the true implementation class (of private hidden type _GDDD) that contains the data and has a single memory occurrence thanks to the unicity table.
Member Typedef Documentation
typedef Valuation::const_iterator GDDD::const_iterator
To hide how arcs are stored.
Also for more compact expressions : use GDDD::const_iterator to iterate over the arcs of a DDD
typedef std::vector<std::pair<int,GDDD> > GDDD::Valuation
To hide how arcs are actually stored. Use GDDD::Valuation to refer to arcs type.
Constructor & Destructor Documentation
GDDD::GDDD (const _GDDD * _g) [private]
A private constructor used in internals.
Parameters:
_g The pointer provided should point into the unicity table
GDDD::GDDD (_GDDD * _g) [private]
UNIMPLEMENTED DELIBERATELY: see SHom.h for details.
user should use version above const & or below const * into unique storage.
GDDD::GDDD (const _GDDD & _g) [private]
GDDD::GDDD (int variable, Valuation value)
Construct a GDDD with arguments given.
Todo:
why is this public ??? WARNING Valuation should be sorted according to arc values
Parameters:
variable the variable labeling the node
value the set of arcs of the node
References canonical, concret, GDDD(), and null.
GDDD::GDDD () [inline]
Default constructor creates the empty set DDD.
Referenced by GDDD().
GDDD::GDDD (int var, int val, const GDDD & d = one)
The most common way for the user of creating DDD.
This constructor builds a node with a single arc of the form var-val->d. Usually a user will create these single path DDD, possibly by imbrication as in GDDD(var1, val1, GDDD(var2, val2)). Then compose them using +, -, *, ^ ...
Parameters:
var the variable labeling the node
val the value labeling the arc
d the successor node or defaults to terminal GDDD::one if none provided
References canonical, concret, null, and _GDDD::valuation.
GDDD::GDDD (int var, int val1, int val2, const GDDD & d = one)
To create a DDD with arcs covering a range of values.
This interface creates nodes with a set of arcs bearing the values in the interval [val1,var2] that point to the same successor node d.
Parameters:
var the variable labeling the node
val1 lowest value labeling an arc
val2 highest value labeling an arc
d the successor node or defaults to terminal GDDD::one if none provided
References canonical, concret, null, and _GDDD::valuation.
Member Function Documentation
GDDD::const_iterator GDDD::begin () const
API for iterating over the arcs of a DDD manually.
i.e. not using a predefined evaluation mechanism such as StrongHom
for (GDDD::const_iterator it = a_gddd.begin() ; it != a_gddd.end() ; it++) { // do something }
returns the first arc
References concret, and _GDDD::valuation.
Referenced by dotExporter::collect(), StrongMLHom::eval(), StrongHom::eval(), _DED_Concat::eval(), _DED_Minus::eval(), _DED_Mult::eval(), _GHom::eval_skip(), MySize::mysize(), MyNbStates::nbStates(), print(), saveNode(), and SddSize::sddsize().
GDDD::const_iterator GDDD::end () const
API for iterating over the arcs of a DDD manually.
i.e. not using a predefined evaluation mechanism such as StrongHom
for (GDDD::const_iterator it = a_gddd.begin() ; it != a_gddd.end() ; it++) { // do something }
returns a past the end iterator
References concret, and _GDDD::valuation.
Referenced by dotExporter::collect(), StrongMLHom::eval(), StrongHom::eval(), _DED_Concat::eval(), _DED_Minus::eval(), _DED_Mult::eval(), _GHom::eval_skip(), MySize::mysize(), MyNbStates::nbStates(), print(), saveNode(), and SddSize::sddsize().
void GDDD::garbage () [static]
For garbage collection, do not call this directly, use MemoryManager::garbage() instead.
Todo:
describe garbage collection algorithm(s) + mark usage homogeneously in one place.
References MyNbStates::clear(), _GDDD::marking, Max_DDD, UniqueTable< T >::size(), and UniqueTable< T >::table.
const std::string GDDD::getvarName (int var) [static]
Gets a variable's name.
Todo:
This function should be implemented in a name manager somewhere so that it is common to DDD and SDD variables.
Parameters:
var the index of the variable to be named
Returns:
the name attached to this variable index
References mapVarName.
Referenced by dotExporter::collect(), and print().
size_t GDDD::hash () const [inline]
For storage in a hash table.
References concret, and ddd::knuth32_hash().
Referenced by _DED_Mult::create(), nsMLHom::LeftConcat::hash(), Minus::hash(), RightConcat::hash(), LeftConcat::hash(), Mult::hash(), Constant::hash(), _DED_Hom::hash(), _DED_Concat::hash(), _DED_Minus::hash(), _DED_Mult::hash(), _DED_GDDD::hash(), and DDD::set_hash().
void GDDD::mark () const
For garbage collection internals.
Marks a GDDD as in use in garbage collection phase.
References concret, and _GDDD::mark().
Referenced by MemoryManager::mark(), Minus::mark(), RightConcat::mark(), LeftConcat::mark(), Mult::mark(), and Constant::mark().
size_t GDDD::nbsons () const
Returns the number of successors of a given node. This is the size of the arc array of the node.
References concret, and _GDDD::valuation.
Referenced by _DED_Minus::eval(), and _DED_Mult::eval().
long double GDDD::nbStates () const
Returns the number of states or paths represented by a given node.
Referenced by Statistic::load(), and DDD::set_size().
unsigned long int GDDD::nodeIndex (const std::vector< const _GDDD * > & list) const [private]
Another function used in serialization.
References concret.
Referenced by saveNode().
long double GDDD::noSharedSize () const
Returns the number of nodes that would be used to represent a DDD if no unicity table was used.
bool GDDD::operator!= (const GDDD & g) const [inline]
Comparison between DDD.
Note that comparison is based on "concret" address in unicity table.
Parameters:
g the node to compare to
Returns:
true if the nodes are not equal.
References concret.
bool GDDD::operator< (const GDDD & g) const [inline]
Total ordering function between DDD.
Note that comparison is based on "concret" address in unicity table. This ordering is necessary for hash and map storage of GDDD.
Parameters:
g the node to compare to
Returns:
true if argument g is greater than "this" node.
References concret.
bool GDDD::operator== (const GDDD & g) const [inline]
Comparison between DDD.
Note that comparison is based on "concret" address in unicity table.
Parameters:
g the node to compare to
Returns:
true if the nodes are equal.
References concret.
Referenced by DDD::empty().
size_t GDDD::peak () [static]
Returns the peak size of the DDD unicity table. This value is maintained up to date upon GarbageCollection.
References Max_DDD, and UniqueTable< T >::size().
Referenced by Statistic::load(), and pstats().
void GDDD::print (std::ostream & os, std::string s) const [private]
Internal function used in recursion for textual printing of GDDD.
References begin(), end(), getvarName(), null, one, top, and variable().
Referenced by operator<<().
void GDDD::pstats (bool reinit = true) [static]
Prints some statistics to std::cout.
Mostly used in debug and development phase. See also MemoryManager::pstats().
Todo:
allow output in other place than cout. Clean up output.
References peak().
unsigned int GDDD::refCounter () const
Returns current reference count of a node.
Reference count corresponds to the number of DDD that use a given concrete node. No recursive reference counting is used : son nodes may have refCount=0 even if this node has a positive refCounter.
References concret, and _GDDD::refCounter.
void GDDD::saveNode (std::ostream & os, std::vector< const _GDDD * > & list) const [private]
A function for DDD serialization (beta).
References begin(), concret, end(), nodeIndex(), null, one, and top.
unsigned long int GDDD::size () const
Returns the size in number of nodes of a DDD structure.
Referenced by Statistic::load().
unsigned int GDDD::statistics () [static]
Returns unicity table current size. Gives the number of different nodes created and not yet destroyed.
References UniqueTable< T >::size().
Referenced by MemoryManager::nbDDD().
int GDDD::variable () const
Returns a node's variable.
References concret, and _GDDD::variable.
Referenced by dotExporter::collect(), _DED_Minus::create(), _DED_Mult::create(), StrongMLHom::eval(), StrongHom::eval(), Fixpoint::eval(), Add::eval(), _DED_Concat::eval(), _DED_Minus::eval(), _DED_Mult::eval(), _GHom::eval_skip(), and print().
void GDDD::varName (int var, const std::string & name) [static]
Sets a variable's name.
Todo:
This function should be implemented in a name manager somewhere so that it is common to DDD and SDD variables.
Parameters:
var the index of the variable to be named
name the name to attach to this variable index
References mapVarName.
Friends And Related Function Documentation
friend class DDD [friend]
Open access to concret for reference counting in DDD.
void loadDDD (std::istream & is, std::vector< DDD > & list) [friend]
Function for deserialization. Load a set of DDD from a stream.
std::ostream& operator<< (std::ostream & os, const GDDD & g) [friend]
A textual output.
Don't use it with large number of paths as each element is printed on a different line
void saveDDD (std::ostream & os, std::vector< DDD > list) [friend]
Function for serialization. Save a set of DDD to a stream.
Member Data Documentation
const _GDDD* GDDD::concret [private]
The real implementation class.
All true operations are delagated on this pointer. Construction/destruction take care of ensuring concret is only instantiated once in memory.
Referenced by begin(), DDD::DDD(), end(), GDDD(), hash(), mark(), nbsons(), nodeIndex(), operator!=(), operator<(), DDD::operator=(), operator==(), refCounter(), saveNode(), variable(), and DDD::~DDD().
const GDDD GDDD::null [static]
The non-accepting terminal.
As DDD are a zero-suppressed variant of decision diagrams, paths leading to null are suppressed. Only the empty set is represented by null.
Referenced by GHom::add(), dotExporter::collect(), _DED_Hom::create(), _DED_Concat::create(), _DED_Minus::create(), _DED_Mult::create(), _DED_Add::create(), DDD::empty(), sns::LocalApply::eval(), StrongHom::eval(), Fixpoint::eval(), Add::eval(), NotCond::eval(), Constant::eval(), _DED_Minus::eval(), _DED_Mult::eval(), _GHom::eval_skip(), GDDD(), _GHom::invert(), loadDDD(), localApply(), MyNbStates::nbStates(), operator&(), GHom::operator()(), print(), saveDDD(), and saveNode().
const GDDD GDDD::one [static]
The accepting terminal. This is the basic leaf for accepted sequences.
Referenced by dotExporter::collect(), _DED_Concat::create(), _DED_Minus::create(), _DED_Mult::create(), _DED_Add::create(), StrongHom::eval(), Fixpoint::eval(), Add::eval(), NotCond::eval(), _GHom::eval_skip(), loadDDD(), MyNbStates::nbStates(), print(), saveDDD(), and saveNode().
const GDDD GDDD::top [static]
The approximation terminal.
This represents *any* finite set of assignment sequences. In a "normal" usage pattern, top terminals should not be produced.
Referenced by dotExporter::collect(), _DED_Concat::create(), _DED_Minus::create(), _DED_Mult::create(), _DED_Add::create(), StrongHom::eval(), Fixpoint::eval(), Add::eval(), NotCond::eval(), _GHom::eval_skip(), loadDDD(), MyNbStates::nbStates(), StrongHom::phiOne(), print(), saveDDD(), and saveNode().
The documentation for this class was generated from the following files:
DDD.h
DDD.cpp
Please comment this page and report errors about it on the RefDocComments page.