DDD: Add Class Reference
Add Class Reference
Public Types
typedef std::set< GHom > param_t
typedef param_t::const_iterator param_it
typedef std::pair< GHom, param_t > partition
typedef std::map< int, partition > partition_cache_type
Public Member Functions
Add (const std::set< GHom > &param, int ref=0)
bool get_have_id () const
param_t & get_parameters ()
partition get_partition (int var)
GHom invert (const GDDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
bool operator== (const _GHom &h) const
Comparator.
size_t hash () const
Hash key computation.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
_GHom * clone () const
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
GDDD eval (const GDDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
virtual GHom compose (const GHom &r) const
Protected Member Functions
const _GHom * get_concret (const GHom &ghom) const
Private Attributes
param_t parameters
partition_cache_type partition_cache
bool have_id
Member Typedef Documentation
typedef param_t::const_iterator Add::param_it
typedef std::set<GHom> Add::param_t
typedef std::pair< GHom , param_t > Add::partition
typedef std::map<int,partition> Add::partition_cache_type
Constructor & Destructor Documentation
Add::Add (const std::set< GHom > & param, int ref = 0) [inline]
References _GHom::get_concret(), and parameters.
Referenced by clone().
Member Function Documentation
_GHom* Add::clone () const [inline, virtual]
Implements _GHom.
References Add().
GHom _GHom::compose (const GHom & r) const [virtual, inherited]
References _GHom::GHom.
Referenced by GHom::compose().
GDDD Add::eval (const GDDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GHom.
References DED::add(), GDDD::null, GDDD::one, parameters, partition_cache, skip_variable(), GDDD::top, and GDDD::variable().
const _GHom* _GHom::get_concret (const GHom & ghom) const [inline, protected, inherited]
References GHom::concret.
Referenced by Add(), Fixpoint::eval(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), skip_variable(), and NotCond::skip_variable().
bool Add::get_have_id () const [inline]
References GHom::id, and parameters.
Referenced by Fixpoint::eval().
param_t& Add::get_parameters () [inline]
References parameters.
partition Add::get_partition (int var) [inline]
References partition_cache, and skip_variable().
Referenced by Fixpoint::eval().
size_t Add::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
References parameters.
GHom Add::invert (const GDDD &) const [inline, virtual]
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented from _GHom.
References GHom::add(), and parameters.
bool Add::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GHom.
References parameters.
void Add::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GHom.
References parameters, and partition_cache.
bool Add::operator== (const _GHom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GHom.
References parameters.
void Add::print (std::ostream & os) const [inline, virtual]
Implements _GHom.
References parameters.
bool Add::skip_variable (int) const [inline, virtual]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GHom.
References GHom::add(), _GHom::get_concret(), parameters, partition_cache, and _GHom::skip_variable().
Referenced by eval(), and get_partition().
Member Data Documentation
bool Add::have_id [private]
param_t Add::parameters [private]
Referenced by Add(), eval(), get_have_id(), get_parameters(), hash(), invert(), is_selector(), mark(), operator==(), print(), and skip_variable().
partition_cache_type Add::partition_cache [mutable, private]
Referenced by eval(), get_partition(), mark(), and skip_variable().
The documentation for this class was generated from the following file:
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.