DDD: ext_hash_map< Key, Data, HashKey, EqualKey >::accessor Class Reference
ext_hash_map< Key, Data, HashKey, EqualKey >::accessor Class Reference
#include <util/ext_hash_map.hh>
Public Types
typedef std::pair< const Key,
Data > value_type
Public Member Functions
value_type & operator* () const
value_type * operator-> () const
bool empty () const
void release ()
Private Attributes
iterator current_bucket_
Friends
class ext_hash_map
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>>
class ext_hash_map< Key, Data, HashKey, EqualKey >::accessor
Member Typedef Documentation
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> typedef std::pair<const Key, Data> ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::value_type
Reimplemented from ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor.
Member Function Documentation
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> bool ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor::empty () const [inline, inherited]
References ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor::has_result_.
Referenced by SDED::eval(), DED::eval(), MySDDNbStates::nbStates(), and MyNbStates::nbStates().
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> value_type& ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator* () const [inline]
Reimplemented from ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor.
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::current_bucket_.
Referenced by ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator->().
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> value_type* ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator-> () const [inline]
Reimplemented from ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor.
References ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator*().
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> void ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor::release () [inline, inherited]
Friends And Related Function Documentation
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> friend class ext_hash_map [friend]
Reimplemented from ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor.
Member Data Documentation
template<typename Key, typename Data, typename HashKey = d3::util::hash<Key>, typename EqualKey = d3::util::equal<Key>> iterator ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::current_bucket_ [private]
Reimplemented from ext_hash_map< Key, Data, HashKey, EqualKey >::const_accessor.
Referenced by ext_hash_map< Key, Data, HashKey, EqualKey >::accessor::operator*().
The documentation for this class was generated from the following file:
util/ext_hash_map.hh
Please comment this page and report errors about it on the RefDocComments page.