DDD: Hom Class Reference
Hom Class Reference
This is the user interface class to manipulate homomorphisms.
#include <Hom.h>
Public Types
typedef GDDD NodeType
Public Member Functions
GHom invert (const GDDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
GDDD operator() (const GDDD &d) const
Evaluation operator.
GDDD eval (const GDDD &d) const
Evaluation function : users should use operator() instead of this.
bool skip_variable (int var) const
GHom compose (const GHom &r) const
int refCounter () const
Accessor to visualize the reference count of the concret instance.
Public Constructors.
Default constructor builds identity homomorphism.
Hom (const GHom &h=GHom::id)
Build an Hom from a GHom.
Hom (const Hom &h)
Copy constructor. Maintains reference count.
Hom (const GDDD &d)
Constructs a constant homomorphism.
Hom (int var, int val, const GHom &h=GHom::id)
Left concatenation of a single arc DDD.
~Hom ()
Destructor maintains reference counting.
Assignment operators.
Hom & operator= (const GHom &)
Overloaded behavior for assignment operator, maintains reference counting.
Hom & operator= (const Hom &)
Overloaded behavior for assignment operator, maintains reference counting.
Comparisons for hash and map storage
bool operator== (const GHom &h) const
Comparison between Homomorphisms.
bool operator!= (const GHom &h) const
Comparison between Homomorphisms.
bool operator< (const GHom &h) const
Total ordering function between Hom.
bool is_selector () const
This predicate is true if the homomorphism global behavior is only to prune some paths.
Static Public Member Functions
static GHom add (const std::set< GHom > &set)
A constructor for a union of several homomorphisms.
Static Public Attributes
static const GHom id
Elementary homomorphism Identity, defined as a constant.
Friends
std::ostream & operator<< (std::ostream &os, const GHom &h)
Memory Management
void mark () const
For garbage collection internals. Marks a GHom as in use in garbage collection phase.
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Returns unicity table current size. Gives the number of different _GHom created and not yet destroyed.
static void pstats (bool reinit=true)
Prints some statistics to std::cout.
static void garbage ()
For garbage collection.
Detailed Description
This is the user interface class to manipulate homomorphisms.
The only difference with Hom is that it implements reference counting so that instances of Hom are not collected upon MemoryManager::garbage().
Member Typedef Documentation
typedef GDDD GHom::NodeType [inherited]
Constructor & Destructor Documentation
Hom::Hom (const GHom & h = GHom::id)
Build an Hom from a GHom.
References GHom::concret, and _GHom::refCounter.
Hom::Hom (const Hom & h)
Copy constructor. Maintains reference count.
References GHom::concret, and _GHom::refCounter.
Hom::Hom (const GDDD & d)
Constructs a constant homomorphism.
References GHom::concret, and _GHom::refCounter.
Hom::Hom (int var, int val, const GHom & h = GHom::id)
Left concatenation of a single arc DDD.
This is provided as a convenience and to avoid the inefficiency if we build a node pointing to GSDD::one and then concatenate something to it. Applied to a SDD d, this homomorphism will return var--val->h(d).
Parameters:
var the variable labeling the node to left concat
val the set of values labeling the arc
h the homomorphism to apply on the argument d. This defaults to GSHom::id.
References GHom::concret, and _GHom::refCounter.
Hom::~Hom ()
Destructor maintains reference counting.
Note that the destructor does not truly reclaim memory, MemoryManager::garbage() does that.
References GHom::concret, and _GHom::refCounter.
Member Function Documentation
GHom GHom::add (const std::set< GHom > & set) [static, inherited]
A constructor for a union of several homomorphisms.
Note that for canonisation and optimization reasons, union is an n-ary and commutative composition operator. Use of this constructor may be slightly more efficient than using operator+ multiple times. H({h1,h2, ..hn}) (d) = sum_i h_i (d).
Parameters:
set the set of homomorphisms to put in the union.
Todo:
std::set not very efficient for storage, replace by a sorted vector ?
References canonical, GHom::GHom(), and GDDD::null.
Referenced by Add::invert(), operator+(), and Add::skip_variable().
GHom GHom::compose (const GHom & r) const [inherited]
References _GHom::compose(), and GHom::concret.
Referenced by nsMLHom::ConstantUp::eval().
GDDD GHom::eval (const GDDD & d) const [inherited]
Evaluation function : users should use operator() instead of this.
This evaluation function does not use the cache, it is called in case of cache miss in the call to operator().
Parameters:
d the argument DDD
Returns:
h(d)
References GHom::concret, and _GHom::eval_skip().
Referenced by _DED_Hom::eval().
void GHom::garbage () [static, inherited]
For garbage collection.
WARNING Do not use this function directly !! Use MemoryManager::garbage() to ensure proper reference counting and cache cleanup. Garbage collection algorithm is a simple two phase mark and sweep : in phase mark, all nodes with positive reference counts are marked, as well as their descendants, recursively. In phase sweep, all nodes which are unmarked are destroyed. This avoids maintaining reference counts during operation : only external references made through the DDD class are counted, and no recursive reference counting is needed.
References Cache< HomType, NodeType >::clear(), _GHom::marking, and UniqueTable< T >::table.
size_t GHom::hash () const [inline, inherited]
For storage in a hash table.
References GHom::concret, and ddd::knuth32_hash().
Referenced by sns::LocalApply::hash(), nsMLHom::ConstantUp::hash(), nsMLHom::GHomAdapter::hash(), Fixpoint::hash(), Minus::hash(), RightConcat::hash(), LeftConcat::hash(), Compose::hash(), NotCond::hash(), Mult::hash(), and _DED_Hom::hash().
GHom GHom::invert (const GDDD & pot) const [inherited]
returns the predescessor homomorphism, using pot to determine variable domains
References GHom::concret, and _GHom::invert().
Referenced by sns::LocalApply::invert(), Fixpoint::invert(), Minus::invert(), Compose::invert(), and Mult::invert().
bool GHom::is_selector () const [inherited]
This predicate is true if the homomorphism global behavior is only to prune some paths.
References GHom::concret, and _GHom::is_selector().
Referenced by sns::LocalApply::is_selector(), Fixpoint::is_selector(), Minus::is_selector(), Compose::is_selector(), Mult::is_selector(), ITE(), and operator!().
void GHom::mark () const [inherited]
For garbage collection internals. Marks a GHom as in use in garbage collection phase.
References GHom::concret, _GHom::mark(), and _GHom::marking.
Referenced by sns::LocalApply::mark(), MemoryManager::mark(), Fixpoint::mark(), Minus::mark(), RightConcat::mark(), LeftConcat::mark(), Compose::mark(), NotCond::mark(), and Mult::mark().
bool GHom::operator!= (const GHom & h) const [inline, inherited]
Comparison between Homomorphisms.
Note that comparison is based on "concret" address in unicity table.
Parameters:
h the hom to compare to
Returns:
true if the nodes are NOT equal.
References GHom::concret.
GDDD GHom::operator() (const GDDD & d) const [inherited]
Evaluation operator.
Homomorphisms overload operator(), so they can be directly applied to DDD nodes. Note that evaluation through this operator uses and updates a cache.
Parameters:
d the DDD to apply this h to.
Returns:
h(d), the result of applying this h to d.
References GHom::concret, _GHom::eval(), _GHom::immediat, Cache< HomType, NodeType >::insert(), and GDDD::null.
bool GHom::operator< (const GHom & h) const [inline, inherited]
Total ordering function between Hom.
Note that comparison is based on "concret" address in unicity table. This ordering is necessary for hash and map storage of GHom.
Parameters:
h the node to compare to
Returns:
true if argument h is greater than "this".
References GHom::concret.
Hom & Hom::operator= (const Hom & h)
Overloaded behavior for assignment operator, maintains reference counting.
References GHom::concret, and _GHom::refCounter.
Hom & Hom::operator= (const GHom & h)
Overloaded behavior for assignment operator, maintains reference counting.
References GHom::concret, and _GHom::refCounter.
bool GHom::operator== (const GHom & h) const [inline, inherited]
Comparison between Homomorphisms.
Note that comparison is based on "concret" address in unicity table.
Parameters:
h the hom to compare to
Returns:
true if the nodes are equal.
References GHom::concret.
void GHom::pstats (bool reinit = true) [static, inherited]
Prints some statistics to std::cout.
Mostly used in debug and development phase.
Todo:
allow output in other place than cout. Clean up output.
References UniqueTable< T >::size(), and UniqueTable< T >::table.
int GHom::refCounter () const [inherited]
Accessor to visualize the reference count of the concret instance.
See _GHom::refCounter for details.
References GHom::concret, and _GHom::refCounter.
bool GHom::skip_variable (int var) const [inherited]
References GHom::concret, and _GHom::skip_variable().
Referenced by nsMLHom::GHomAdapter::skip_variable().
unsigned int GHom::statistics () [static, inherited]
Returns unicity table current size. Gives the number of different _GHom created and not yet destroyed.
References UniqueTable< T >::size().
Referenced by Statistic::load(), and MemoryManager::nbHom().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const GHom & h) [friend, inherited]
Member Data Documentation
const GHom GHom::id [static, inherited]
Elementary homomorphism Identity, defined as a constant.
id(d) = d
Referenced by buildUnionParameters(), nsMLHom::GHomAdapter::eval(), nsMLHom::Identity::eval(), fixpoint(), Add::get_have_id(), Fixpoint::invert(), Minus::invert(), Mult::invert(), localApply(), and operator&().
The documentation for this class was generated from the following files:
Hom.h
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.