DDD: StrongHom Class Reference
StrongHom Class Reference
The abstract base class for user defined operations.
#include <Hom.h>
Public Member Functions
StrongHom ()
Default constructor.
virtual ~StrongHom ()
Default destructor.
virtual GDDD phiOne () const
Evaluation over terminal GDDD::one.
virtual GHom phi (int var, int val) const =0
Evaluation over an arbitrary arc of a SDD.
virtual bool operator== (const StrongHom &h) const =0
Comparator is pure virtual. Define a behavior in user homomorphisms.
bool operator== (const _GHom &h) const
Comparator for unicity table.
virtual void print (std::ostream &os) const
pretty print
GDDD eval (const GDDD &) const
The evaluation mechanism of strong homomorphisms.
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual GHom invert (const GDDD &) const
returns the predescessor homomorphism, using pot to determine variable domains
virtual size_t hash () const =0
Hash key computation.
virtual _GHom * clone () const =0
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GHom compose (const GHom &r) const
Protected Member Functions
const _GHom * get_concret (const GHom &ghom) const
Detailed Description
The abstract base class for user defined operations.
This is the class users should derive their operations from. It defines the interface of a Strong Homomorphism : evaluation over terminal GDDD::one, which should return a constant DDD evaluation over an arbitrary var--val--> pair, that returns a homomorphism to apply to the successor node Users also have to provide a comparison function, and a hash function (from _GHom). See the demo folder for examples of user defined homomorphisms.
Constructor & Destructor Documentation
StrongHom::StrongHom () [inline]
Default constructor.
Empty behavior.
Todo:
Is this declaration useful ?
virtual StrongHom::~StrongHom () [inline, virtual]
Default destructor.
Empty behavior.
Todo:
Is this declaration useful ?
Member Function Documentation
virtual _GHom* _GHom::clone () const [pure virtual, inherited]
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
GHom _GHom::compose (const GHom & r) const [virtual, inherited]
References _GHom::GHom.
Referenced by GHom::compose().
GDDD StrongHom::eval (const GDDD & d) const [virtual]
The evaluation mechanism of strong homomorphisms.
Evaluation is defined as :
Let an SDD d= (var, Union_i (val_i, d_i))
h (d) = Sum_i (phi(var, val_i) (d_i))
Implements _GHom.
References DED::add(), GDDD::begin(), GDDD::end(), GDDD::null, GDDD::one, phi(), phiOne(), GDDD::top, and GDDD::variable().
const _GHom* _GHom::get_concret (const GHom & ghom) const [inline, protected, inherited]
References GHom::concret.
Referenced by Add::Add(), Fixpoint::eval(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
virtual size_t _GHom::hash () const [pure virtual, inherited]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implemented in Identity, Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
virtual GHom _GHom::invert (const GDDD &) const [inline, virtual, inherited]
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented in Identity, Constant, Mult, Add, Compose, Minus, and Fixpoint.
References _GHom::GHom, _GHom::is_selector(), GDDD::null, and _GHom::print().
Referenced by GHom::invert().
virtual bool _GHom::is_selector () const [inline, virtual, inherited]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in Identity, Mult, NotCond, Add, Compose, Minus, and Fixpoint.
Referenced by _GHom::invert(), and GHom::is_selector().
virtual void _GHom::mark () const [inline, virtual, inherited]
For garbage collection. Used in first phase of garbage collection.
Reimplemented in Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
Referenced by GHom::mark().
bool StrongHom::operator== (const _GHom & h) const [virtual]
Comparator for unicity table.
Users should not use this. The behavior is to check for type mismatch (and return false if that is the case) or call specialized comparators of derived subclasses otherwise.
Implements _GHom.
virtual bool StrongHom::operator== (const StrongHom & h) const [pure virtual]
Comparator is pure virtual. Define a behavior in user homomorphisms.
virtual GHom StrongHom::phi (int var, int val) const [pure virtual]
Evaluation over an arbitrary arc of a SDD.
Parameters:
var the index of the variable labeling the node.
val the value labeling the arc.
Returns:
a homomorphism to apply on the successor node
Referenced by eval().
virtual GDDD StrongHom::phiOne () const [inline, virtual]
Evaluation over terminal GDDD::one.
Returns a constant DDD. A homomorphism that does not overload phiOne does not expect to meet the terminal during it's evaluation, therefore default behavior returns GDDD::top
References GDDD::top.
Referenced by eval().
void StrongHom::print (std::ostream & os) const [virtual]
pretty print
Implements _GHom.
virtual bool _GHom::skip_variable (int) const [inline, virtual, inherited]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in Identity, NotCond, Add, Compose, RightConcat, and Fixpoint.
Referenced by _GHom::eval_skip(), GHom::skip_variable(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
The documentation for this class was generated from the following files:
Hom.h
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.