DDD: _SDED_GSDD Class Reference
_SDED_GSDD Class Reference
Public Member Functions
_SDED_GSDD (const GSDD &g)
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
Private Attributes
GSDD parameter
Constructor & Destructor Documentation
_SDED_GSDD::_SDED_GSDD (const GSDD & g) [inline]
Referenced by clone().
Member Function Documentation
_SDED* _SDED_GSDD::clone () const [inline, virtual]
Implements _SDED.
References _SDED_GSDD().
GSDD _SDED_GSDD::eval () const [inline, virtual]
Implements _SDED.
References parameter.
size_t _SDED_GSDD::hash () const [inline, virtual]
Implements _SDED.
References GSDD::hash(), and parameter.
bool _SDED_GSDD::operator== (const _SDED & e) const [inline, virtual]
Implements _SDED.
References parameter.
Member Data Documentation
GSDD _SDED_GSDD::parameter [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.