DDD: sns::LeftConcat Class Reference
sns::LeftConcat Class Reference
Public Member Functions
LeftConcat (const GSDD &l, const GShom &r, int ref=0)
bool operator== (const _GShom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Private Attributes
GSDD left
GShom right
Constructor & Destructor Documentation
sns::LeftConcat::LeftConcat (const GSDD & l, const GShom & r, int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_GShom* sns::LeftConcat::clone () const [inline, virtual]
Implements _GShom.
References LeftConcat().
GSDD sns::LeftConcat::eval (const GSDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References left, and right.
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
virtual const GShom::range_t _GShom::get_range () const [inline, virtual, inherited]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, and sns::Fixpoint.
References GShom::full_range.
Referenced by GShom::get_range().
size_t sns::LeftConcat::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References GShom::hash(), GSDD::hash(), left, and right.
virtual GShom _GShom::invert (const GSDD &) const [inline, virtual, inherited]
Reimplemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::And, sns::Add, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
virtual bool _GShom::is_selector () const [inline, virtual, inherited]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
Referenced by _GShom::invert(), and GShom::is_selector().
void sns::LeftConcat::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References left, GShom::mark(), GSDD::mark(), and right.
bool sns::LeftConcat::operator== (const _GShom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References left, and right.
void sns::LeftConcat::print (std::ostream & os) const [inline, virtual]
Implements _GShom.
References left, and right.
virtual bool _GShom::skip_variable (int) const [inline, virtual, inherited]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in sns::Identity, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::RightConcat, and sns::Fixpoint.
Referenced by _GShom::eval_skip(), GShom::skip_variable(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
Member Data Documentation
GSDD sns::LeftConcat::left [private]
Referenced by eval(), hash(), mark(), operator==(), and print().
GShom sns::LeftConcat::right [private]
Referenced by eval(), hash(), mark(), operator==(), and print().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.