DDD: _SDED_Concat Class Reference
_SDED_Concat Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
~_SDED_Concat ()
Static Public Member Functions
static _SDED * create (const GSDD &g1, const GSDD &g2)
Private Member Functions
_SDED_Concat (const GSDD &g1, const GSDD &g2)
Private Attributes
GSDD parameter1
GSDD parameter2
Constructor & Destructor Documentation
_SDED_Concat::_SDED_Concat (const GSDD & g1, const GSDD & g2) [inline, private]
Referenced by clone(), and create().
_SDED_Concat::~_SDED_Concat () [inline]
Member Function Documentation
_SDED* _SDED_Concat::clone () const [inline, virtual]
Implements _SDED.
References _SDED_Concat().
_SDED * _SDED_Concat::create (const GSDD & g1, const GSDD & g2) [static]
References _SDED_Concat(), GSDD::null, GSDD::one, and GSDD::top.
Referenced by operator^().
GSDD _SDED_Concat::eval () const [virtual]
Implements _SDED.
References GSDD::begin(), GSDD::end(), GSDD::null, parameter1, parameter2, square_union(), and GSDD::variable().
size_t _SDED_Concat::hash () const [virtual]
Implements _SDED.
References GSDD::hash(), parameter1, and parameter2.
bool _SDED_Concat::operator== (const _SDED & e) const [virtual]
Implements _SDED.
References parameter1, and parameter2.
Member Data Documentation
GSDD _SDED_Concat::parameter1 [private]
Referenced by eval(), hash(), and operator==().
GSDD _SDED_Concat::parameter2 [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.