DDD: sns::Mult Class Reference
sns::Mult Class Reference
Public Member Functions
Mult (const GShom &l, const GSDD &r, int ref=0)
bool operator== (const _GShom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GShom * clone () const
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GShom invert (const GSDD &pot) const
void mark () const
For garbage collection. Used in first phase of garbage collection.
void print (std::ostream &os) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Private Attributes
GShom left
GSDD right
Constructor & Destructor Documentation
sns::Mult::Mult (const GShom & l, const GSDD & r, int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_GShom* sns::Mult::clone () const [inline, virtual]
Implements _GShom.
References Mult().
GSDD sns::Mult::eval (const GSDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
optimized evaluation when left.skip : prune at current level and drop a recursive call i.e. do OTF intersection with the constant
CODE COPY PASTE FROM SDED_MULT OF 2 SDD : TODO : REFACTOR THIS ALGO TO SHARE CODE
Implements _GShom.
References GSDD::begin(), DataSet::empty(), GSDD::end(), left, GSDD::null, right, GShom::skip_variable(), square_union(), and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
virtual const GShom::range_t _GShom::get_range () const [inline, virtual, inherited]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, and sns::Fixpoint.
References GShom::full_range.
Referenced by GShom::get_range().
size_t sns::Mult::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References GSDD::hash(), GShom::hash(), left, and right.
GShom sns::Mult::invert (const GSDD & pot) const [inline, virtual]
Reimplemented from _GShom.
References GShom::id, GShom::invert(), left, and right.
bool sns::Mult::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
References GShom::is_selector(), and left.
void sns::Mult::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References left, GSDD::mark(), GShom::mark(), and right.
bool sns::Mult::operator== (const _GShom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References left, and right.
void sns::Mult::print (std::ostream & os) const [inline, virtual]
Implements _GShom.
References left, and right.
virtual bool _GShom::skip_variable (int) const [inline, virtual, inherited]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in sns::Identity, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::RightConcat, and sns::Fixpoint.
Referenced by _GShom::eval_skip(), GShom::skip_variable(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
Member Data Documentation
GShom sns::Mult::left [private]
Referenced by eval(), hash(), invert(), is_selector(), mark(), operator==(), and print().
GSDD sns::Mult::right [private]
Referenced by eval(), hash(), invert(), mark(), operator==(), and print().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.