DDD: Shom Class Reference
Shom Class Reference
This is the user interface class to manipulate homomorphisms.
#include <SHom.h>
Public Types
enum fixpointStrategy { BFS, DFS }
typedef GSDD NodeType
Public Member Functions
GShom invert (const GSDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
int refCounter () const
For debug and development purposes. Gives the reference count of the concrete data.
Public Constructors.
Default constructor builds identity homomorphism.
Shom (const GShom &h=GShom::id)
Build an Shom from a GShom.
Shom (const Shom &h)
Copy constructor. Maintains reference count.
Shom (const GSDD &d)
Constructs a constant homomorphism.
Shom (int var, const DataSet &val, const GShom &h=GShom::id)
Left concatenation of a single arc SDD.
~Shom ()
Destructor maintains reference counting.
Assignment operators.
Shom & operator= (const GShom &)
Overloaded behavior for assignment operator, maintains reference counting.
Shom & operator= (const Shom &)
Overloaded behavior for assignment operator, maintains reference counting.
Evaluation mechanism for homomorphisms.
GSDD operator() (const GSDD &d) const
Applying a homomorphism to a node returns a node.
GSDD eval (const GSDD &d) const
The full evaluation, this is the computational procedure, that is called when the computation cache yields a miss.
Static Public Member Functions
static GShom add (const d3::set< GShom >::type &s)
Compute an n-ary sum between homomorphisms.
static fixpointStrategy getFixpointStrategy ()
static void setFixpointStrategy (fixpointStrategy strat)
Static Public Attributes
static const Shom null = GSDD::null
static const GShom id
Elementary SDD homomorphism identity. Applied to any SDD d, it returns d.
Friends
std::ostream & operator<< (std::ostream &os, const GShom &h)
Comparisons between GShom.
Comparisons between GShom for unicity table.
Both equality comparison and total ordering provided to allow hash and map storage of GShom
static const range_t full_range = GShom::range_t()
The full_range : that targets everyone.
bool operator== (const GShom &h) const
bool operator!= (const GShom &h) const
bool operator< (const GShom &h) const
bool is_selector () const
This predicate is true if the homomorphism global behavior is only to prune some paths.
bool skip_variable (int) const
This predicate is true if the homomorphism "skips" this variable.
const range_t get_range () const
Returns the range for this homomorphism, i.e. the dual of skip_variable.
typedef d3::set< int >::type range_t
typedef range_t::const_iterator range_it
Memory Management routines.
void mark () const
Mark a concrete data as in use (forbids garbage collection of the data).
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Return the current size of the unicity table for GShom.
static size_t cache_size ()
Return the current size of the cache for GShom.
static void pstats (bool reinit=true)
Print some usage statistics on Shom.
static void garbage ()
Collects and destroys unused homomorphisms.
Detailed Description
This is the user interface class to manipulate homomorphisms.
The only difference with GShom is that it implements reference counting so that instances of Shom are not collected upon MemoryManager::garbage().
Member Typedef Documentation
typedef GSDD GShom::NodeType [inherited]
typedef range_t::const_iterator GShom::range_it [inherited]
typedef d3::set<int>::type GShom::range_t [inherited]
Member Enumeration Documentation
enum GShom::fixpointStrategy [inherited]
Enumerator:
BFS
DFS
Constructor & Destructor Documentation
Shom::Shom (const GShom & h = GShom::id)
Build an Shom from a GShom.
References GShom::concret, and _GShom::refCounter.
Shom::Shom (const Shom & h)
Copy constructor. Maintains reference count.
References GShom::concret, and _GShom::refCounter.
Shom::Shom (const GSDD & d)
Constructs a constant homomorphism.
References GShom::concret, and _GShom::refCounter.
Shom::Shom (int var, const DataSet & val, const GShom & h = GShom::id)
Left concatenation of a single arc SDD.
This is provided as a convenience and to avoid the inefficiency if we build a node pointing to GSDD::one and then concatenate something to it. Applied to a SDD d, this homomorphism will return var--val->h(d).
Parameters:
var the variable labeling the node to left concat
val the set of values labeling the arc
h the homomorphism to apply on the argument d. This defaults to GSHom::id.
References GShom::concret, and _GShom::refCounter.
Shom::~Shom ()
Destructor maintains reference counting.
Note that the destructor does not truly reclaim memory, MemoryManager::garbage() does that.
References GShom::concret, and _GShom::refCounter.
Member Function Documentation
static GShom GShom::add (const d3::set< GShom >::type & s) [static, inherited]
Compute an n-ary sum between homomorphisms.
This should be slightly more efficient in evaluation than a composition of binary sums constructed using the friend operator+.
Todo:
: move this to friend status not static member for more homogeneity with other operators.
size_t GShom::cache_size () [static, inherited]
Return the current size of the cache for GShom.
References sns::cache.
Referenced by Statistic::load().
GSDD GShom::eval (const GSDD & d) const [inherited]
The full evaluation, this is the computational procedure, that is called when the computation cache yields a miss.
Users should not use this function directly, but only through GSDD::operator().
References GShom::concret, and _GShom::eval_skip().
Referenced by _SDED_Shom::eval(), and GShom::operator()().
void GShom::garbage () [static, inherited]
Collects and destroys unused homomorphisms.
Do not call this directly but through MemoryManager::garbage() as order of calls (among GSDD::garbage(), GShom::garbage(), SDED::garbage()) is important.
References sns::cache, canonical, and _GShom::marking.
const GShom::range_t GShom::get_range () const [inherited]
Returns the range for this homomorphism, i.e. the dual of skip_variable.
References GShom::concret, and _GShom::get_range().
Referenced by commutative(), fixpoint(), sns::Fixpoint::get_range(), sns::Compose::get_range(), sns::SNotCond::get_range(), and notInRange().
static fixpointStrategy GShom::getFixpointStrategy () [inline, static, inherited]
References GShom::fixpointStrategy_.
Referenced by sns::Fixpoint::eval().
size_t GShom::hash () const [inline, inherited]
For storage in a hash table.
References GShom::concret, and ddd::knuth32_hash().
Referenced by sns::Fixpoint::hash(), sns::HomMinus::hash(), sns::Minus::hash(), sns::RightConcat::hash(), sns::LeftConcat::hash(), sns::Compose::hash(), sns::SNotCond::hash(), sns::SLocalApply::hash(), sns::Inter::hash(), sns::Mult::hash(), and _SDED_Shom::hash().
GShom GShom::invert (const GSDD & pot) const [inherited]
returns the predescessor homomorphism, using pot to determine variable domains
References GShom::concret, and _GShom::invert().
Referenced by sns::Fixpoint::invert(), sns::HomMinus::invert(), sns::Minus::invert(), sns::Compose::invert(), sns::SLocalApply::invert(), sns::Inter::invert(), and sns::Mult::invert().
bool GShom::is_selector () const [inherited]
This predicate is true if the homomorphism global behavior is only to prune some paths.
References GShom::concret, and _GShom::is_selector().
Referenced by commutative(), fixpoint(), sns::Fixpoint::is_selector(), sns::HomMinus::is_selector(), sns::Minus::is_selector(), sns::Compose::is_selector(), sns::SLocalApply::is_selector(), sns::Inter::is_selector(), sns::Mult::is_selector(), ITE(), operator!(), and operator*().
void GShom::mark () const [inherited]
Mark a concrete data as in use (forbids garbage collection of the data).
References GShom::concret, _GShom::mark(), and _GShom::marking.
Referenced by sns::Fixpoint::eval(), sns::Fixpoint::mark(), sns::HomMinus::mark(), sns::Minus::mark(), sns::RightConcat::mark(), sns::LeftConcat::mark(), sns::Compose::mark(), sns::SNotCond::mark(), sns::SLocalApply::mark(), sns::Inter::mark(), and sns::Mult::mark().
bool GShom::operator!= (const GShom & h) const [inline, inherited]
References GShom::concret.
GSDD GShom::operator() (const GSDD & d) const [inherited]
Applying a homomorphism to a node returns a node.
This is the normal way for users of computing the application of a homomorphism.
References sns::cache, GShom::concret, GShom::eval(), _GShom::immediat, and GSDD::null.
bool GShom::operator< (const GShom & h) const [inline, inherited]
References GShom::concret.
Shom & Shom::operator= (const Shom & h)
Overloaded behavior for assignment operator, maintains reference counting.
References GShom::concret, and _GShom::refCounter.
Shom & Shom::operator= (const GShom & h)
Overloaded behavior for assignment operator, maintains reference counting.
References GShom::concret, and _GShom::refCounter.
bool GShom::operator== (const GShom & h) const [inline, inherited]
References GShom::concret.
void GShom::pstats (bool reinit = true) [static, inherited]
Print some usage statistics on Shom.
Mostly used for development and debug.
Todo:
Allow output not in std::cout.
References canonical.
int GShom::refCounter () const [inherited]
For debug and development purposes. Gives the reference count of the concrete data.
References GShom::concret, and _GShom::refCounter.
static void GShom::setFixpointStrategy (fixpointStrategy strat) [inline, static, inherited]
References GShom::fixpointStrategy_.
bool GShom::skip_variable (int var) const [inherited]
This predicate is true if the homomorphism "skips" this variable.
References GShom::concret, and _GShom::skip_variable().
Referenced by sns::Mult::eval(), sns::Fixpoint::skip_variable(), sns::Compose::skip_variable(), and sns::SNotCond::skip_variable().
unsigned int GShom::statistics () [static, inherited]
Return the current size of the unicity table for GShom.
References canonical.
Referenced by Statistic::load(), and MemoryManager::nbShom().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const GShom & h) [friend, inherited]
Member Data Documentation
const GShom::range_t GShom::full_range = GShom::range_t() [static, inherited]
The full_range : that targets everyone.
Referenced by _GShom::get_range().
const GShom GShom::id [static, inherited]
Elementary SDD homomorphism identity. Applied to any SDD d, it returns d.
Referenced by buildUnionParameters(), sns::Fixpoint::eval(), sns::And::eval(), _GShom::eval_skip(), fixpoint(), sns::Fixpoint::invert(), sns::HomMinus::invert(), sns::Minus::invert(), sns::And::invert(), sns::Mult::invert(), localApply(), operator!(), and operator&().
const Shom Shom::null = GSDD::null [static]
Referenced by GShom::GShom(), _GShom::invert(), localApply(), operator!(), operator&(), and operator*().
The documentation for this class was generated from the following files:
SHom.h
SDD.cpp
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.