DDD: sns::DomExtract Class Reference
sns::DomExtract Class Reference
Extractor of variable domains for invert computations.
Public Member Functions
DomExtract ()
DomExtract (int t)
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
size_t hash () const
Hash key computation.
bool operator== (const _GShom &s) const
Comparator.
_GShom * clone () const
void print (std::ostream &os) const
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Public Attributes
int target
Detailed Description
Extractor of variable domains for invert computations.
Constructor & Destructor Documentation
sns::DomExtract::DomExtract () [inline]
Referenced by clone().
sns::DomExtract::DomExtract (int t) [inline]
Member Function Documentation
_GShom* sns::DomExtract::clone () const [inline, virtual]
Implements _GShom.
References DomExtract().
GSDD sns::DomExtract::eval (const GSDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References SDED::add(), GSDD::begin(), GSDD::end(), GSDD::null, GSDD::one, target, GSDD::top, and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
const GShom::range_t sns::DomExtract::get_range () const [inline, virtual]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GShom.
size_t sns::DomExtract::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References target.
virtual GShom _GShom::invert (const GSDD &) const [inline, virtual, inherited]
Reimplemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::And, sns::Add, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
bool sns::DomExtract::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
virtual void _GShom::mark () const [inline, virtual, inherited]
For garbage collection. Used in first phase of garbage collection.
Reimplemented in sns::Constant, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, and sns::Fixpoint.
Referenced by GShom::mark().
bool sns::DomExtract::operator== (const _GShom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References target.
void sns::DomExtract::print (std::ostream & os) const [inline, virtual]
Implements _GShom.
References target.
bool sns::DomExtract::skip_variable (int) const [inline, virtual]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
Member Data Documentation
int sns::DomExtract::target
Referenced by eval(), hash(), operator==(), and print().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.