DDD: nsMLHom::ConstantUp Class Reference
nsMLHom::ConstantUp Class Reference
Public Member Functions
ConstantUp (const GHom &uup, const MLHom &ddown)
bool operator== (const _MLHom &other) const
_MLHom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
GHom up
MLHom down
Constructor & Destructor Documentation
nsMLHom::ConstantUp::ConstantUp (const GHom & uup, const MLHom & ddown) [inline]
Referenced by clone().
Member Function Documentation
_MLHom* nsMLHom::ConstantUp::clone () const [inline, virtual]
Implements _MLHom.
References ConstantUp().
HomNodeMap nsMLHom::ConstantUp::eval (const GDDD & d) const [inline, virtual]
Implements _MLHom.
References AdditiveMap< K, V >::add(), AdditiveMap< K, V >::begin(), GHom::compose(), down, AdditiveMap< K, V >::end(), and up.
size_t nsMLHom::ConstantUp::hash () const [inline, virtual]
unique table trivia
Implements _MLHom.
References down, MLHom::hash(), GHom::hash(), and up.
bool nsMLHom::ConstantUp::operator== (const _MLHom & other) const [inline, virtual]
Implements _MLHom.
References down, and up.
virtual bool _MLHom::shouldCache () const [inline, virtual, inherited]
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
bool nsMLHom::ConstantUp::skip_variable (int) const [inline]
Member Data Documentation
MLHom nsMLHom::ConstantUp::down [private]
Referenced by eval(), hash(), and operator==().
GHom nsMLHom::ConstantUp::up [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.