DDD: StrongShom Class Reference
StrongShom Class Reference
The abstract base class for user defined operations.
#include <SHom.h>
Public Member Functions
StrongShom ()
Default constructor.
virtual ~StrongShom ()
Default destructor.
virtual GSDD phiOne () const
Evaluation over terminal GSDD::one.
virtual GShom phi (int var, const DataSet &val) const =0
Evaluation over an arbitrary arc of a SDD.
virtual bool operator== (const StrongShom &h) const =0
Comparator is pure virtual. Define a behavior in user homomorphisms.
bool operator== (const _GShom &h) const
Comparator for unicity table.
virtual void print (std::ostream &os) const
pretty print
GSDD eval (const GSDD &) const
The evaluation mechanism of strong homomorphisms.
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
virtual const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
virtual size_t hash () const =0
Hash key computation.
virtual _GShom * clone () const =0
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GShom invert (const GSDD &) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Detailed Description
The abstract base class for user defined operations.
This is the class users should derive their operations from. It defines the interface of a Strong Homomorphism : evaluation over terminal GSDD::one, which should return a constant SDD evaluation over an arbitrary var--val--> pair, that returns a homomorphism to apply to the successor node Users also have to provide a comparison function, and a hash function (from _GShom). See the demo folder for examples of user defined homomorphisms.
Constructor & Destructor Documentation
StrongShom::StrongShom () [inline]
Default constructor.
Empty behavior.
Todo:
Is this declaration useful ?
virtual StrongShom::~StrongShom () [inline, virtual]
Default destructor.
Empty behavior.
Todo:
Is this declaration useful ?
Member Function Documentation
virtual _GShom* _GShom::clone () const [pure virtual, inherited]
Implemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, and sns::Fixpoint.
GSDD StrongShom::eval (const GSDD & d) const [virtual]
The evaluation mechanism of strong homomorphisms.
Evaluation is defined as :
Let an SDD d= (var, Union_i (val_i, d_i))
h (d) = Sum_i (phi(var, val_i) (d_i))
Implements _GShom.
References SDED::add(), GSDD::begin(), GSDD::end(), GSDD::null, GSDD::one, phi(), phiOne(), GSDD::top, and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
virtual const GShom::range_t _GShom::get_range () const [inline, virtual, inherited]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented in sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, and sns::Fixpoint.
References GShom::full_range.
Referenced by GShom::get_range().
virtual size_t _GShom::hash () const [pure virtual, inherited]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, and sns::Fixpoint.
virtual GShom _GShom::invert (const GSDD &) const [inline, virtual, inherited]
Reimplemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::And, sns::Add, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
References _GShom::is_selector(), Shom::null, and _GShom::print().
Referenced by GShom::invert().
virtual bool _GShom::is_selector () const [inline, virtual, inherited]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented in sns::Identity, sns::Constant, sns::Mult, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::Minus, sns::HomMinus, and sns::Fixpoint.
Referenced by _GShom::invert(), and GShom::is_selector().
virtual void _GShom::mark () const [inline, virtual, inherited]
For garbage collection. Used in first phase of garbage collection.
Reimplemented in sns::Constant, sns::Mult, sns::Inter, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::LeftConcat, sns::RightConcat, sns::Minus, sns::HomMinus, and sns::Fixpoint.
Referenced by GShom::mark().
bool StrongShom::operator== (const _GShom & h) const [virtual]
Comparator for unicity table.
Users should not use this. The behavior is to check for type mismatch (and return false if that is the case) or call specialized comparators of derived subclasses otherwise.
Implements _GShom.
virtual bool StrongShom::operator== (const StrongShom & h) const [pure virtual]
Comparator is pure virtual. Define a behavior in user homomorphisms.
virtual GShom StrongShom::phi (int var, const DataSet & val) const [pure virtual]
Evaluation over an arbitrary arc of a SDD.
Parameters:
var the index of the variable labeling the node.
val the set of values labeling the arc.
Returns:
a homomorphism to apply on the successor node
Referenced by eval().
virtual GSDD StrongShom::phiOne () const [inline, virtual]
Evaluation over terminal GSDD::one.
Returns a constant SDD. A homomorphism that does not overload phiOne does not expect to meet the terminal during it's evaluation, therefore default behavior returns GSDD::top
References GSDD::top.
Referenced by eval().
void StrongShom::print (std::ostream & os) const [virtual]
pretty print
Implements _GShom.
virtual bool _GShom::skip_variable (int) const [inline, virtual, inherited]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in sns::Identity, sns::Inter, sns::DomExtract, sns::LocalApply, sns::SLocalApply, sns::SNotCond, sns::And, sns::Add, sns::Compose, sns::RightConcat, and sns::Fixpoint.
Referenced by _GShom::eval_skip(), GShom::skip_variable(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
The documentation for this class was generated from the following files:
SHom.h
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.