DDD: Minus Class Reference
Minus Class Reference
Public Member Functions
Minus (const GHom &l, const GDDD &r, int ref=0)
bool operator== (const _GHom &h) const
Comparator.
size_t hash () const
Hash key computation.
_GHom * clone () const
GDDD eval (const GDDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GHom invert (const GDDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
void print (std::ostream &os) const
virtual bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
virtual GHom compose (const GHom &r) const
Protected Member Functions
const _GHom * get_concret (const GHom &ghom) const
Private Attributes
GHom left
GDDD right
Constructor & Destructor Documentation
Minus::Minus (const GHom & l, const GDDD & r, int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_GHom* Minus::clone () const [inline, virtual]
Implements _GHom.
References Minus().
GHom _GHom::compose (const GHom & r) const [virtual, inherited]
References _GHom::GHom.
Referenced by GHom::compose().
GDDD Minus::eval (const GDDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GHom.
References left, and right.
const _GHom* _GHom::get_concret (const GHom & ghom) const [inline, protected, inherited]
References GHom::concret.
Referenced by Add::Add(), Fixpoint::eval(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
size_t Minus::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
References GDDD::hash(), GHom::hash(), left, and right.
GHom Minus::invert (const GDDD &) const [inline, virtual]
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented from _GHom.
References GHom::id, GHom::invert(), left, and right.
bool Minus::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GHom.
References GHom::is_selector(), and left.
void Minus::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GHom.
References left, GDDD::mark(), GHom::mark(), and right.
bool Minus::operator== (const _GHom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GHom.
References left, and right.
void Minus::print (std::ostream & os) const [inline, virtual]
Implements _GHom.
References left, and right.
virtual bool _GHom::skip_variable (int) const [inline, virtual, inherited]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented in Identity, NotCond, Add, Compose, RightConcat, and Fixpoint.
Referenced by _GHom::eval_skip(), GHom::skip_variable(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
Member Data Documentation
GHom Minus::left [private]
Referenced by eval(), hash(), invert(), is_selector(), mark(), operator==(), and print().
GDDD Minus::right [private]
Referenced by eval(), hash(), invert(), mark(), operator==(), and print().
The documentation for this class was generated from the following file:
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.