DDD: sns::SLocalApply Class Reference
sns::SLocalApply Class Reference
Public Member Functions
SLocalApply ()
SLocalApply (const GShom &hh, int t)
bool skip_variable (int var) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
const GShom::range_t get_range () const
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
GSDD eval (const GSDD &d) const
The computation function responsible for evaluation over a node.
void mark () const
For garbage collection. Used in first phase of garbage collection.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
size_t hash () const
Hash key computation.
GShom invert (const GSDD &pot) const
bool operator== (const _GShom &s) const
Comparator.
_GShom * clone () const
void print (std::ostream &os) const
Static Public Member Functions
static const _GShom * get_concret (const GShom &gshom)
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
Public Attributes
GShom h
int target
Constructor & Destructor Documentation
sns::SLocalApply::SLocalApply () [inline]
Referenced by clone().
sns::SLocalApply::SLocalApply (const GShom & hh, int t) [inline]
Member Function Documentation
_GShom* sns::SLocalApply::clone () const [inline, virtual]
Implements _GShom.
References SLocalApply().
GSDD sns::SLocalApply::eval (const GSDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GShom.
References SDED::add(), GSDD::begin(), GSDD::end(), h, GSDD::null, GSDD::one, GSDD::top, and GSDD::variable().
static const _GShom* _GShom::get_concret (const GShom & gshom) [inline, static, inherited]
TODO : this is a dirty trick to allow us to do terms rewriting in Add, Fixpoint etc.
.. A more elegant architecture would be nice.
References GShom::concret.
Referenced by addCompositionParameter(), addParameter(), buildUnionParameters(), sns::Fixpoint::eval(), sns::Add::factorizeByLevel(), fixpoint(), GShom::GShom(), operator!(), sns::RightConcat::skip_variable(), sns::Add::skip_variable(), and sns::Inter::skip_variable().
const GShom::range_t sns::SLocalApply::get_range () const [inline, virtual]
The range returns the dual of skip_variable, default implem considers that all variables are affected by this homomorphism.
Reimplemented from _GShom.
References target.
size_t sns::SLocalApply::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GShom.
References h, GShom::hash(), and target.
GShom sns::SLocalApply::invert (const GSDD & pot) const [inline, virtual]
Reimplemented from _GShom.
References GSDD::begin(), _GShom::GShom, h, GShom::invert(), localApply(), and target.
bool sns::SLocalApply::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GShom.
References h, and GShom::is_selector().
void sns::SLocalApply::mark () const [inline, virtual]
For garbage collection. Used in first phase of garbage collection.
Reimplemented from _GShom.
References h, and GShom::mark().
bool sns::SLocalApply::operator== (const _GShom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GShom.
References h, and target.
void sns::SLocalApply::print (std::ostream & os) const [inline, virtual]
Implements _GShom.
References h, and target.
bool sns::SLocalApply::skip_variable (int) const [inline, virtual]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GShom.
References target.
Member Data Documentation
GShom sns::SLocalApply::h
Referenced by addParameter(), eval(), hash(), invert(), is_selector(), mark(), operator==(), and print().
int sns::SLocalApply::target
Referenced by addParameter(), get_range(), hash(), invert(), operator==(), print(), and skip_variable().
The documentation for this class was generated from the following file:
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.