DDD: _SDED_Shom Class Reference
_SDED_Shom Class Reference
Public Member Functions
size_t hash () const
bool operator== (const _SDED &e) const
_SDED * clone () const
GSDD eval () const
~_SDED_Shom ()
Static Public Member Functions
static _SDED * create (const GShom &h, const GSDD &d)
Private Member Functions
_SDED_Shom (const GShom &h, const GSDD &d)
Private Attributes
GShom shom
GSDD parameter
Constructor & Destructor Documentation
_SDED_Shom::_SDED_Shom (const GShom & h, const GSDD & d) [inline, private]
Referenced by clone(), and create().
_SDED_Shom::~_SDED_Shom () [inline]
Member Function Documentation
_SDED* _SDED_Shom::clone () const [inline, virtual]
Implements _SDED.
References _SDED_Shom().
_SDED * _SDED_Shom::create (const GShom & h, const GSDD & d) [static]
References _SDED_Shom(), and GSDD::null.
Referenced by SDED::Shom().
GSDD _SDED_Shom::eval () const [virtual]
Implements _SDED.
References GShom::eval(), parameter, and shom.
size_t _SDED_Shom::hash () const [virtual]
Implements _SDED.
References GSDD::hash(), GShom::hash(), parameter, and shom.
bool _SDED_Shom::operator== (const _SDED & e) const [virtual]
Implements _SDED.
References parameter, and shom.
Member Data Documentation
GSDD _SDED_Shom::parameter [private]
Referenced by eval(), hash(), and operator==().
GShom _SDED_Shom::shom [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
SDED.cpp
Please comment this page and report errors about it on the RefDocComments page.