DDD: Identity Class Reference
Identity Class Reference
Public Member Functions
Identity (int ref=0)
bool operator== (const _GHom &) const
Comparator.
size_t hash () const
Hash key computation.
_GHom * clone () const
bool skip_variable (int) const
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
bool is_selector () const
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
GHom invert (const GDDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
void print (std::ostream &os) const
GDDD eval (const GDDD &d) const
The computation function responsible for evaluation over a node.
virtual void mark () const
For garbage collection. Used in first phase of garbage collection.
virtual GHom compose (const GHom &r) const
Protected Member Functions
const _GHom * get_concret (const GHom &ghom) const
Constructor & Destructor Documentation
Identity::Identity (int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_GHom* Identity::clone () const [inline, virtual]
Implements _GHom.
References Identity().
GHom _GHom::compose (const GHom & r) const [virtual, inherited]
References _GHom::GHom.
Referenced by GHom::compose().
GDDD Identity::eval (const GDDD &) const [inline, virtual]
The computation function responsible for evaluation over a node.
Users should not directly use this. Normal behavior is to use GShom::operator() that encapsulates this call with operation caching.
Implements _GHom.
const _GHom* _GHom::get_concret (const GHom & ghom) const [inline, protected, inherited]
References GHom::concret.
Referenced by Add::Add(), Fixpoint::eval(), Fixpoint::skip_variable(), RightConcat::skip_variable(), Compose::skip_variable(), Add::skip_variable(), and NotCond::skip_variable().
size_t Identity::hash () const [inline, virtual]
Hash key computation.
It is essential for good hash table operation that the spread of the keys be as good as possible. Also, fast hash key computation is a good design goal. Note that bad hash functions will yield more collisions, thus equality comparisons which may be quite costly.
Implements _GHom.
GHom Identity::invert (const GDDD &) const [inline, virtual]
returns the predescessor homomorphism, using pot to determine variable domains
Reimplemented from _GHom.
bool Identity::is_selector () const [inline, virtual]
The isSelector predicate indicates a homomorphism that only selects paths in the SDD (no modifications, no additions) Tagging with isSelector() allows to enable optimizations and makes the homomorphism eligible as "condition" in ITE construct.
Reimplemented from _GHom.
virtual void _GHom::mark () const [inline, virtual, inherited]
For garbage collection. Used in first phase of garbage collection.
Reimplemented in Constant, Mult, NotCond, Add, Compose, LeftConcat, RightConcat, Minus, Fixpoint, and MLHomAdapter.
Referenced by GHom::mark().
bool Identity::operator== (const _GHom & h) const [inline, virtual]
Comparator.
Used in case of hash collision. Should be appropriately defined in derived classes, in particular in user defined homomorphisms.
Implements _GHom.
void Identity::print (std::ostream & os) const [inline, virtual]
Implements _GHom.
bool Identity::skip_variable (int) const [inline, virtual]
The skip_variable predicate indicates which variables are "don't care" with respect to this SHom.
This is defined as a StrongHom with : phi(var,val) { if (skip_variable(var)) return GShom(var, val, this); else { real behavior } }
Reimplemented from _GHom.
The documentation for this class was generated from the following file:
Hom.cpp
Please comment this page and report errors about it on the RefDocComments page.