DDD: GShom Class Reference
GShom Class Reference
This class is the base class for Homomorphisms over SDD.
#include <SHom.h>
Public Types
enum fixpointStrategy { BFS, DFS }
typedef GSDD NodeType
Public Member Functions
GShom invert (const GSDD &pot) const
returns the predescessor homomorphism, using pot to determine variable domains
int refCounter () const
For debug and development purposes. Gives the reference count of the concrete data.
Public Constructors
GShom ()
Default constructor builds identity homomorphism.
GShom (const _GShom *_h)
Pseudo-private constructor.
GShom (_GShom *_h)
THIS VERSION IS DELIBERATELY UNIMPLEMENTED OTHERWISE bad calls like GShom(new myHom()) would promote to const _GShom *_h and bypass unicity.
GShom (const _GShom &_h)
To build GShom from pointers to user homomomorphisms.
GShom (const GSDD &d)
Construct a constant homomorphism.
GShom (int var, const DataSet &val, const GShom &h=GShom::id)
Left concatenation of a single arc SDD.
Evaluation mechanism for homomorphisms.
GSDD operator() (const GSDD &d) const
Applying a homomorphism to a node returns a node.
GSDD eval (const GSDD &d) const
The full evaluation, this is the computational procedure, that is called when the computation cache yields a miss.
Static Public Member Functions
static GShom add (const d3::set< GShom >::type &s)
Compute an n-ary sum between homomorphisms.
static fixpointStrategy getFixpointStrategy ()
static void setFixpointStrategy (fixpointStrategy strat)
Static Public Attributes
static const GShom id
Elementary SDD homomorphism identity. Applied to any SDD d, it returns d.
Private Attributes
const _GShom * concret
Pointer to the data instance in the unicity table.
Static Private Attributes
static fixpointStrategy fixpointStrategy_ = BFS
Friends
class Shom
Open access to concret for Shom class.
class _GShom
Open access to _GShom based homomophisms.
std::ostream & operator<< (std::ostream &os, const GShom &h)
Friendly hard coded composition operators.
Open full access for library implemented hard coded operations.
GShom fixpoint (const GShom &, bool is_top_level)
Apply a homomorphism until fixpoint is reached.
GShom localApply (const GHom &, int target)
Apply a homomorphism on a target variable.
GShom localApply (const GShom &, int target)
GShom add (const d3::set< GShom >::type &)
GShom operator+ (const GShom &, const GShom &)
Composition by union of two homomorphisms.
GShom operator& (const GShom &, const GShom &)
Composition by circ (rond) of homomorphisms.
GShom operator* (const GSDD &, const GShom &)
Intersection with a constant SDD.
GShom operator* (const GShom &, const GSDD &)
Intersection with a constant SDD.
GShom operator^ (const GSDD &, const GShom &)
Left Concatenation of a constant SDD.
GShom operator^ (const GShom &, const GSDD &)
Right Concatenation of a constant SDD.
GShom operator- (const GShom &, const GSDD &)
Set difference.
Comparisons between GShom.
Comparisons between GShom for unicity table.
Both equality comparison and total ordering provided to allow hash and map storage of GShom
typedef d3::set< int >::type range_t
typedef range_t::const_iterator range_it
static const range_t full_range = GShom::range_t()
The full_range : that targets everyone.
bool operator== (const GShom &h) const
bool operator!= (const GShom &h) const
bool operator< (const GShom &h) const
bool is_selector () const
This predicate is true if the homomorphism global behavior is only to prune some paths.
bool skip_variable (int) const
This predicate is true if the homomorphism "skips" this variable.
const range_t get_range () const
Returns the range for this homomorphism, i.e. the dual of skip_variable.
Memory Management routines.
void mark () const
Mark a concrete data as in use (forbids garbage collection of the data).
size_t hash () const
For storage in a hash table.
static unsigned int statistics ()
Return the current size of the unicity table for GShom.
static size_t cache_size ()
Return the current size of the cache for GShom.
static void pstats (bool reinit=true)
Print some usage statistics on Shom.
static void garbage ()
Collects and destroys unused homomorphisms.
Detailed Description
This class is the base class for Homomorphisms over SDD.
Composition operators between homomorphisms are defined at this level, so this is the common ground between user-defined homomorphisms (i.e. derived classes of StrongShom) and hard-coded operations such as union, concatenation etc... Like GSDD, GShom implement a smart pointer behavior, the actual data (instance of hidden private class _GShom) linked to an instance of GShom has only one occurrence in memory, thanks to a unicity table.
User homomorphisms should be manipulated and instanciated using Shom, as GShom provide no reference counting and are thus likely to be collected in a MemoryManager::garbage() call. Shom provides reference counting.
Member Typedef Documentation
typedef GSDD GShom::NodeType
typedef range_t::const_iterator GShom::range_it
typedef d3::set<int>::type GShom::range_t
Member Enumeration Documentation
enum GShom::fixpointStrategy
Enumerator:
BFS
DFS
Constructor & Destructor Documentation
GShom::GShom () [inline]
Default constructor builds identity homomorphism.
GShom::GShom (const _GShom * _h)
Pseudo-private constructor.
This should only be called with pointers into the unicity table. For example return this in a StrongHom phi() body is legal.
Parameters:
_h pointer into the unicity table
GShom::GShom (_GShom * _h)
THIS VERSION IS DELIBERATELY UNIMPLEMENTED OTHERWISE bad calls like GShom(new myHom()) would promote to const _GShom *_h and bypass unicity.
User code prior to 20/05/08 would use this in the form : return new myHom(xx); This is now illegal as we take up memory allocation now, so the user should stack alloc and pass a reference as in GShom(const _GShom &_h). Exceptionally, for efficiency, return this; in a phi user function is permitted hence public visibility of above GShom(const _GShom *_h); This signature is here to ensure link errors in old user code.
GShom::GShom (const _GShom & _h)
To build GShom from pointers to user homomomorphisms.
This call ensures unicity of representation.
GShom::GShom (const GSDD & d)
Construct a constant homomorphism.
Applied to any SDD this homomorphism will return the value it was initialized with.
GShom::GShom (int var, const DataSet & val, const GShom & h = GShom::id)
Left concatenation of a single arc SDD.
This is provided as a convenience and to avoid the inefficiency if we build a node pointing to GSDD::one and then concatenate something to it. Applied to a SDD d, this homomorphism will return var--val->h(d).
Parameters:
var the variable labeling the node to left concat
val the set of values labeling the arc
h the homomorphism to apply on the argument d. This defaults to GSHom::id.
References canonical, concret, DataSet::empty(), _GShom::get_concret(), and Shom::null.
Member Function Documentation
static GShom GShom::add (const d3::set< GShom >::type & s) [static]
Compute an n-ary sum between homomorphisms.
This should be slightly more efficient in evaluation than a composition of binary sums constructed using the friend operator+.
Todo:
: move this to friend status not static member for more homogeneity with other operators.
size_t GShom::cache_size () [static]
Return the current size of the cache for GShom.
References sns::cache.
Referenced by Statistic::load().
GSDD GShom::eval (const GSDD & d) const
The full evaluation, this is the computational procedure, that is called when the computation cache yields a miss.
Users should not use this function directly, but only through GSDD::operator().
References concret, and _GShom::eval_skip().
Referenced by _SDED_Shom::eval(), and operator()().
void GShom::garbage () [static]
Collects and destroys unused homomorphisms.
Do not call this directly but through MemoryManager::garbage() as order of calls (among GSDD::garbage(), GShom::garbage(), SDED::garbage()) is important.
References sns::cache, canonical, and _GShom::marking.
const GShom::range_t GShom::get_range () const
Returns the range for this homomorphism, i.e. the dual of skip_variable.
References concret, and _GShom::get_range().
Referenced by commutative(), fixpoint(), sns::Fixpoint::get_range(), sns::Compose::get_range(), sns::SNotCond::get_range(), and notInRange().
static fixpointStrategy GShom::getFixpointStrategy () [inline, static]
References fixpointStrategy_.
Referenced by sns::Fixpoint::eval().
size_t GShom::hash () const [inline]
For storage in a hash table.
References concret, and ddd::knuth32_hash().
Referenced by sns::Fixpoint::hash(), sns::HomMinus::hash(), sns::Minus::hash(), sns::RightConcat::hash(), sns::LeftConcat::hash(), sns::Compose::hash(), sns::SNotCond::hash(), sns::SLocalApply::hash(), sns::Inter::hash(), sns::Mult::hash(), and _SDED_Shom::hash().
GShom GShom::invert (const GSDD & pot) const
returns the predescessor homomorphism, using pot to determine variable domains
References concret, and _GShom::invert().
Referenced by sns::Fixpoint::invert(), sns::HomMinus::invert(), sns::Minus::invert(), sns::Compose::invert(), sns::SLocalApply::invert(), sns::Inter::invert(), and sns::Mult::invert().
bool GShom::is_selector () const
This predicate is true if the homomorphism global behavior is only to prune some paths.
References concret, and _GShom::is_selector().
Referenced by commutative(), fixpoint(), sns::Fixpoint::is_selector(), sns::HomMinus::is_selector(), sns::Minus::is_selector(), sns::Compose::is_selector(), sns::SLocalApply::is_selector(), sns::Inter::is_selector(), sns::Mult::is_selector(), ITE(), operator!(), and operator*().
void GShom::mark () const
Mark a concrete data as in use (forbids garbage collection of the data).
References concret, _GShom::mark(), and _GShom::marking.
Referenced by sns::Fixpoint::eval(), sns::Fixpoint::mark(), sns::HomMinus::mark(), sns::Minus::mark(), sns::RightConcat::mark(), sns::LeftConcat::mark(), sns::Compose::mark(), sns::SNotCond::mark(), sns::SLocalApply::mark(), sns::Inter::mark(), and sns::Mult::mark().
bool GShom::operator!= (const GShom & h) const [inline]
References concret.
GSDD GShom::operator() (const GSDD & d) const
Applying a homomorphism to a node returns a node.
This is the normal way for users of computing the application of a homomorphism.
References sns::cache, concret, eval(), _GShom::immediat, and GSDD::null.
bool GShom::operator< (const GShom & h) const [inline]
References concret.
bool GShom::operator== (const GShom & h) const [inline]
References concret.
void GShom::pstats (bool reinit = true) [static]
Print some usage statistics on Shom.
Mostly used for development and debug.
Todo:
Allow output not in std::cout.
References canonical.
int GShom::refCounter () const
For debug and development purposes. Gives the reference count of the concrete data.
References concret, and _GShom::refCounter.
static void GShom::setFixpointStrategy (fixpointStrategy strat) [inline, static]
References fixpointStrategy_.
bool GShom::skip_variable (int var) const
This predicate is true if the homomorphism "skips" this variable.
References concret, and _GShom::skip_variable().
Referenced by sns::Mult::eval(), sns::Fixpoint::skip_variable(), sns::Compose::skip_variable(), and sns::SNotCond::skip_variable().
unsigned int GShom::statistics () [static]
Return the current size of the unicity table for GShom.
References canonical.
Referenced by Statistic::load(), and MemoryManager::nbShom().
Friends And Related Function Documentation
friend class _GShom [friend]
Open access to _GShom based homomophisms.
GShom GShom::add (const d3::set< GShom >::type & set) [friend]
Referenced by fixpoint(), sns::Add::invert(), operator+(), and sns::Add::skip_variable().
GShom fixpoint (const GShom & , bool is_top_level) [friend]
Apply a homomorphism until fixpoint is reached.
This new unary operator is introduced to implement local saturation in transition relation evaluation. Proper use of fixpoint allows to effectively tackle the intermediate size problem of decision diagram based representations. Note that evaluation simply iterates until a fixpoint is reached, thus to cumulate new states with previously reached it should be combined with GShom::id as in
fixpoint (h + GShom::id)
GShom localApply (const GShom & , int target) [friend]
GShom localApply (const GHom & , int target) [friend]
Apply a homomorphism on a target variable.
This ensures that the operation is local to this variable, and is used to implement auto-saturation.
GShom operator& (const GShom & , const GShom &) [friend]
Composition by circ (rond) of homomorphisms.
Semantics : (h1 & h2) (d) = h1(h2(d)).
GShom operator* (const GShom & , const GSDD &) [friend]
Intersection with a constant SDD.
Semantics : (d1 * h) (d) = d1 * h(d)
GShom operator* (const GSDD & , const GShom &) [friend]
Intersection with a constant SDD.
Semantics : (h * d1) (d) = h(d) * d1
GShom operator+ (const GShom & , const GShom &) [friend]
Composition by union of two homomorphisms.
See also GShom::add(). This commutative operation computes a homomorphism that evaluates as the sum of two homomorphism.
Semantics : (h1 + h2) (d) = h1(d) + h2(d).
GShom operator- (const GShom & , const GSDD &) [friend]
Set difference.
Note that this operation is not commutative, nor is it linear. This means the difference of two linear homomorphisms is not necessarily linear; (h1 - h2) (d) is not necessarily equal to h1(d) - h2(d). Therefore this operator is not defined for composition of two homomorphisms, only for a constant and a homomorphism.
Semantics : (h - d1) (d) = h(d) - d1
std::ostream& operator<< (std::ostream & os, const GShom & h) [friend]
GShom operator^ (const GShom & , const GSDD &) [friend]
Right Concatenation of a constant SDD.
This is used to construct new nodes, and has the same efficiency issue as left concatenation.
Semantics : (h ^ d1) (d) = h(d) ^ d1
GShom operator^ (const GSDD & , const GShom &) [friend]
Left Concatenation of a constant SDD.
Note that this is inherently inefficient, the nodes of d1 are constructed, but the result a priori will not contain them, unless h(d) == GSDD::one.
Semantics : (d1 ^ h) (d) = d1 ^ h(d)
friend class Shom [friend]
Open access to concret for Shom class.
Member Data Documentation
const _GShom* GShom::concret [private]
Pointer to the data instance in the unicity table.
Referenced by eval(), _GShom::get_concret(), get_range(), GShom(), hash(), invert(), is_selector(), mark(), operator!=(), operator()(), operator<(), operator<<(), Shom::operator=(), operator==(), refCounter(), Shom::Shom(), skip_variable(), and Shom::~Shom().
GShom::fixpointStrategy GShom::fixpointStrategy_ = BFS [static, private]
Referenced by getFixpointStrategy(), and setFixpointStrategy().
const GShom::range_t GShom::full_range = GShom::range_t() [static]
The full_range : that targets everyone.
Referenced by _GShom::get_range().
const GShom GShom::id [static]
Elementary SDD homomorphism identity. Applied to any SDD d, it returns d.
Referenced by buildUnionParameters(), sns::Fixpoint::eval(), sns::And::eval(), _GShom::eval_skip(), fixpoint(), sns::Fixpoint::invert(), sns::HomMinus::invert(), sns::Minus::invert(), sns::And::invert(), sns::Mult::invert(), localApply(), operator!(), and operator&().
The documentation for this class was generated from the following files:
SHom.h
SDD.cpp
SHom.cpp
Please comment this page and report errors about it on the RefDocComments page.