DDD: nsMLHom::Identity Class Reference
nsMLHom::Identity Class Reference
Public Member Functions
Identity (int ref=0)
virtual bool shouldCache () const
test if caching should be done : default means should cache
bool operator== (const _MLHom &) const
size_t hash () const
unique table trivia
_MLHom * clone () const
bool skip_variable (int) const
HomNodeMap eval (const GDDD &d) const
Constructor & Destructor Documentation
nsMLHom::Identity::Identity (int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_MLHom* nsMLHom::Identity::clone () const [inline, virtual]
Implements _MLHom.
References Identity().
HomNodeMap nsMLHom::Identity::eval (const GDDD & d) const [inline, virtual]
Implements _MLHom.
References AdditiveMap< K, V >::add(), and GHom::id.
size_t nsMLHom::Identity::hash () const [inline, virtual]
unique table trivia
Implements _MLHom.
bool nsMLHom::Identity::operator== (const _MLHom &) const [inline, virtual]
Implements _MLHom.
virtual bool nsMLHom::Identity::shouldCache () const [inline, virtual]
test if caching should be done : default means should cache
Reimplemented from _MLHom.
bool nsMLHom::Identity::skip_variable (int) const [inline]
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.