DDD: UniqueTable< T > Class Template Reference
UniqueTable< T > Class Template Reference
This class implements a unicity table mechanism, based on an STL hash_set.
#include <UniqueTable.h>
Public Types
typedef d3::hash_set< const T * >
::type Table
Typedef helps hide implementation type (currently gnu gcc's hash_set).
Public Member Functions
UniqueTable ()
Constructor, builds a default table.
const T * operator() (const T &_g)
The application operator, returns the address of the value already in the table if it exists, or inserts and returns the address of the value inserted.
size_t size () const
Returns the current number of filled entries in the table.
Public Attributes
Table table
The actual table, operations on the UniqueTable are delegated on this.
Detailed Description
template<typename T>
class UniqueTable< T >
This class implements a unicity table mechanism, based on an STL hash_set.
Requirements on the contained type are thus those of hash_set.
Member Typedef Documentation
template<typename T> typedef d3::hash_set<const T*>::type UniqueTable< T >::Table
Typedef helps hide implementation type (currently gnu gcc's hash_set).
Constructor & Destructor Documentation
template<typename T> UniqueTable< T >::UniqueTable () [inline]
Constructor, builds a default table.
Member Function Documentation
template<typename T> const T* UniqueTable< T >::operator() (const T & _g) [inline]
The application operator, returns the address of the value already in the table if it exists, or inserts and returns the address of the value inserted.
Parameters:
_g the pointer to the value we want to find in the table.
Returns:
the address of an object stored in the UniqueTable such that (*_g == *return_value)
template<typename T> size_t UniqueTable< T >::size () const [inline]
Returns the current number of filled entries in the table.
Referenced by GSDD::garbage(), GDDD::garbage(), GSDD::peak(), GDDD::peak(), GHom::pstats(), GSDD::statistics(), GHom::statistics(), and GDDD::statistics().
Member Data Documentation
template<typename T> Table UniqueTable< T >::table
The actual table, operations on the UniqueTable are delegated on this.
Referenced by SDDutil::foreachTable(), GSDD::garbage(), MLHom::garbage(), GHom::garbage(), GDDD::garbage(), UniqueTable< std::vector< int > >::operator()(), GHom::pstats(), and UniqueTable< std::vector< int > >::size().
The documentation for this class was generated from the following file:
UniqueTable.h
Please comment this page and report errors about it on the RefDocComments page.