DDD: nsMLHom::Add Class Reference
nsMLHom::Add Class Reference
Public Member Functions
Add (const std::set< MLHom > &s, int ref=0)
bool operator== (const _MLHom &h) const
_MLHom * clone () const
size_t hash () const
unique table trivia
bool skip_variable (int) const
HomNodeMap eval (const GDDD &d) const
virtual bool shouldCache () const
test if caching should be done : default means should cache
Private Attributes
std::set< MLHom > parameters
Constructor & Destructor Documentation
nsMLHom::Add::Add (const std::set< MLHom > & s, int ref = 0) [inline]
Referenced by clone().
Member Function Documentation
_MLHom* nsMLHom::Add::clone () const [inline, virtual]
Implements _MLHom.
References Add().
HomNodeMap nsMLHom::Add::eval (const GDDD & d) const [inline, virtual]
Implements _MLHom.
References AdditiveMap< K, V >::addAll(), and parameters.
size_t nsMLHom::Add::hash () const [inline, virtual]
unique table trivia
Implements _MLHom.
References parameters.
bool nsMLHom::Add::operator== (const _MLHom & h) const [inline, virtual]
Implements _MLHom.
References parameters.
virtual bool _MLHom::shouldCache () const [inline, virtual, inherited]
test if caching should be done : default means should cache
Reimplemented in nsMLHom::Identity.
bool nsMLHom::Add::skip_variable (int) const [inline]
Member Data Documentation
std::set<MLHom> nsMLHom::Add::parameters [private]
Referenced by eval(), hash(), and operator==().
The documentation for this class was generated from the following file:
MLHom.cpp
Please comment this page and report errors about it on the RefDocComments page.