DDD: SDD.h File Reference
SDD.h File Reference
#include <string>
#include "UniqueTable.h"
#include "DataSet.h"
Classes
class GSDD
This class is the base class representing a hierarchical Set Decision Diagram.
class SDD
This class is the public interface for manipulating Data Decision Diagrams.
struct std::less< GSDD >
Compares two SDD in hash tables.
Namespaces
namespace SDDutil
Namespace declared to hide these functions.
namespace std
Defines
#define HEIGHTSDD
Functions
std::ostream & operator<< (std::ostream &, const GSDD &)
Textual output of SDD into a stream in (relatively) human readable format.
GSDD operator^ (const GSDD &, const GSDD &)
Operator for concatenation of two SDD.
GSDD operator+ (const GSDD &, const GSDD &)
Operator for union of DDD.
GSDD operator* (const GSDD &, const GSDD &)
Operator for intersection of DDD.
GSDD operator- (const GSDD &, const GSDD &)
Operator for set difference of DDD.
UniqueTable< _GSDD > * SDDutil::getTable ()
accessor to UniqueTable instance declared in cpp file, (hem, please don't touch it).
void SDDutil::foreachTable (void(*foo)(const GSDD &g))
Iterator over the entries of the table, applies foo to each entry in the table.
Define Documentation
#define HEIGHTSDD
Function Documentation
GSDD operator* (const GSDD & , const GSDD &)
Operator for intersection of DDD.
Semantics : d1 * d2 designates the intersection of the two sets
References _SDED_Mult::create(), and SDED::eval().
GSDD operator+ (const GSDD & , const GSDD &)
Operator for union of DDD.
Semantics : d1 + d2 produces the union d1 and d2
References _SDED_Add::create(), and SDED::eval().
GSDD operator- (const GSDD & , const GSDD &)
Operator for set difference of DDD.
Semantics : d1 - d2 contains elements in d1 and not in d2
References _SDED_Minus::create(), and SDED::eval().
std::ostream& operator<< (std::ostream & os, const GSDD & g)
Textual output of SDD into a stream in (relatively) human readable format.
A textual output.
Don't use it with large number of paths as each element is printed on a different line
References GSDD::print().
GSDD operator^ (const GSDD & , const GSDD &)
Operator for concatenation of two SDD.
Semantics : d1 ^ d2 replaces "one" terminals of d1 by d2
References _SDED_Concat::create(), and SDED::eval().
Please comment this page and report errors about it on the RefDocComments page.